import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { getSerialBatch, getSerialGeneratorOptions } from "@/lib/inventory/serials";
import { generateSerialBatchAction } from "@/app/admin/serials/actions";

export const dynamic = "force-dynamic";
export default async function SerialGeneratorPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ batch?: string; success?: string; error?: string }> }) {
  const { profile, permissions } = await requirePermission("serials.generate"); const [{ id }, message] = await Promise.all([params, searchParams]);
  const [{ product, warehouses }, batch] = await Promise.all([getSerialGeneratorOptions(id), message.batch ? getSerialBatch(message.batch) : Promise.resolve(null)]);
  if (!product) notFound(); const brand = product.brands as unknown as { name: string } | null; const action = generateSerialBatchAction.bind(null, id);
  return <DashboardShell admin={profile.role === "admin"} employeePermissions={profile.role === "employee" ? permissions : undefined} title="Generate SEN serials" subtitle="Create persisted expected physical units before stock receipt.">
    {message.success ? <p className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-green-900">{message.success}</p> : null}{message.error ? <p className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-red-900">{message.error}</p> : null}
    <section className="mb-6 grid gap-4 rounded-xl border bg-[var(--surface)] p-5 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-sm text-[var(--muted-text)]">Product</span><strong className="block">{product.name}</strong></div><div><span className="text-sm text-[var(--muted-text)]">SKU</span><strong className="block">{product.sku}</strong></div><div><span className="text-sm text-[var(--muted-text)]">Brand</span><strong className="block">{brand?.name ?? "Missing"}</strong></div><div><span className="text-sm text-[var(--muted-text)]">Model</span><strong className="block">{product.model_number ?? "Missing"}</strong></div></section>
    {!product.serial_tracking_required || !brand || !product.model_number ? <p className="rounded border border-amber-300 bg-amber-50 p-4 text-amber-950">Enable serial tracking and provide an active brand and model number on the product before generating labels.</p> : <form action={action} className="grid gap-4 rounded-xl border bg-[var(--surface)] p-6 md:grid-cols-2"><label>Expected warehouse<select name="warehouse_id" required className="mt-1 w-full rounded border p-3"><option value="">Choose warehouse</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="1" max="500" step="1" required defaultValue="1" className="mt-1 w-full rounded border p-3"/></label><label>Condition<input name="condition" defaultValue="new" maxLength={80} className="mt-1 w-full rounded border p-3"/></label><label className="md:col-span-2">Optional manufacturer serials<textarea name="manufacturer_serials" placeholder="One per line; blank values are allowed" className="mt-1 min-h-28 w-full rounded border p-3"/></label><label className="md:col-span-2">Notes<textarea name="notes" className="mt-1 min-h-24 w-full rounded border p-3"/></label><button className="min-h-12 rounded bg-[var(--primary)] px-5 py-3 font-semibold text-[var(--primary-foreground)] md:col-span-2">Generate and persist serials</button></form>}
    {batch ? <section className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Generated batch</h2><p className="text-sm text-[var(--muted-text)]">{batch.units.length} expected units · no on-hand stock added</p></div><div className="flex gap-2"><a className="rounded border px-4 py-2 font-semibold" href={`/admin/serials/print?batch=${batch.batch.id}`}>Print all</a><a className="rounded border px-4 py-2 font-semibold" href={`/admin/serials/export?batch=${batch.batch.id}`}>Download CSV</a></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr><th className="py-2">SEN serial</th><th>Manufacturer serial</th><th>Status</th><th>Actions</th></tr></thead><tbody>{batch.units.map((unit) => <tr key={unit.id} className="border-t"><td className="py-3 font-mono text-xs"><a href={`/admin/serials/${unit.id}`}>{unit.sen_serial}</a></td><td>{unit.manufacturer_serial ?? "Not provided"}</td><td>{unit.status}</td><td><a href={`/admin/serials/print?ids=${unit.id}`} className="font-semibold">Print</a></td></tr>)}</tbody></table></div></section> : null}
  </DashboardShell>;
}
