import { connection } from "next/server";
import { notFound } from "next/navigation";
import { HrPage, hrCard } from "@/components/hr/HrPage";
import { adminRecruitmentDocumentHref, getSubmittedRecruitmentApplication } from "@/lib/hr/admin-recruitment";

export const dynamic = "force-dynamic";

const shown = (value: unknown) => value === true ? "Yes" : value === false ? "No" : typeof value === "string" && value.trim() ? value : value == null ? "Not Provided" : String(value);
const Row = ({ label, value }: { label: string; value: unknown }) => <div><dt className="text-xs font-bold uppercase tracking-wide text-[var(--muted-text)]">{label}</dt><dd className="mt-1 whitespace-pre-wrap font-medium">{shown(value)}</dd></div>;
const documentLabel: Record<string, string> = { photograph: "Photograph", cv: "CV / Resume", nid_copy: "NID Copy", passport_copy: "Passport Copy", education_certificate: "Educational Certificate", experience_certificate: "Experience Certificate", qualification_certificate: "Professional / Training Certificate", other: "Other Supporting Document" };

function DocumentActions({ document }: { document: any }) {
  return <span className="flex flex-wrap gap-3"><a className="font-bold text-blue-700" href={adminRecruitmentDocumentHref(document.id)} target="_blank" rel="noreferrer">View</a><a className="font-bold text-emerald-700" href={adminRecruitmentDocumentHref(document.id, true)}>Download</a></span>;
}

export default async function AdminRecruitmentApplicationPage({ params }: { params: Promise<{ applicationId: string }> }) {
  await connection();
  const { applicationId } = await params;
  const state = await getSubmittedRecruitmentApplication(applicationId);
  if (!state) notFound();
  const a: any = state.application;
  const docs: any[] = state.documents;
  const documentFor = (type: string, related?: string) => docs.find((item) => item.document_type === type && (related === undefined || item.related_record_id === related));
  const photograph = documentFor("photograph");
  return <HrPage title="Recruitment Application" subtitle="Read-only submitted application details.">
    <div className="mb-4"><a className="font-bold text-blue-700" href="/admin/hr/recruitment">← Submitted Applications</a></div>
    <section className={`${hrCard} border-blue-200 bg-blue-50/40`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-blue-700">{a.application_number}</p><h1 className="text-2xl font-bold">{a.full_name}</h1><p>{a.position_applied_for}</p></div><div className="text-right"><span className="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-800">SUBMITTED</span><p className="mt-2 text-sm">{a.submitted_at ? new Date(a.submitted_at).toLocaleString() : "—"}</p></div></div></section>
    <div className="mt-5 space-y-5">
      <section className={hrCard}><h2 className="mb-4 text-xl font-bold">Personal Information</h2><dl className="grid gap-4 md:grid-cols-3"><Row label="Full Name" value={a.full_name}/><Row label="Father's Name" value={a.father_name}/><Row label="Mother's Name" value={a.mother_name}/><Row label="Date of Birth" value={a.date_of_birth}/><Row label="Gender" value={a.gender}/><Row label="Marital Status" value={a.marital_status}/>{a.marital_status === "Married" ? <><Row label="Spouse Name" value={a.spouse_name}/><Row label="Spouse Contact Number" value={a.spouse_contact_number}/></> : null}<Row label="Nationality" value={a.nationality}/><Row label="Phone" value={a.phone}/><Row label="Email" value={a.email}/><Row label="Present Address" value={a.present_address}/><Row label="Permanent Address" value={a.permanent_address}/><Row label="Emergency Contact Name" value={a.emergency_contact_name}/><Row label="Emergency Contact Phone" value={a.emergency_contact_phone}/><Row label="Emergency Contact Relationship" value={a.emergency_contact_relationship}/></dl></section>
      <section className={hrCard}><h2 className="mb-4 text-xl font-bold">Identity</h2>{photograph ? <div className="mb-4"><img className="h-40 w-32 rounded-xl border object-cover" src={adminRecruitmentDocumentHref(photograph.id)} alt={`Recent photograph of ${a.full_name}`} /><div className="mt-2"><DocumentActions document={photograph}/></div></div> : <p className="mb-4">Recent Photograph: Not Provided</p>}<dl className="grid gap-4 md:grid-cols-3"><Row label="NID Number" value={a.nid_number}/><div><dt className="text-xs font-bold uppercase text-[var(--muted-text)]">NID Copy</dt>{documentFor("nid_copy") ? <DocumentActions document={documentFor("nid_copy")}/> : <dd>Not Provided</dd>}</div><Row label="Passport Number" value={a.passport_number}/>{a.passport_number ? <><Row label="Passport Expiry Date" value={a.passport_expiry_date}/><div><dt className="text-xs font-bold uppercase text-[var(--muted-text)]">Passport Copy</dt>{documentFor("passport_copy") ? <DocumentActions document={documentFor("passport_copy")}/> : <dd>Not Provided</dd>}</div></> : null}</dl></section>
      <section className={hrCard}><h2 className="mb-4 text-xl font-bold">Employment / Application</h2><dl className="grid gap-4 md:grid-cols-3"><Row label="Position Applied For" value={a.position_applied_for}/><Row label="Preferred / Available Joining Date" value={a.preferred_joining_date}/><Row label="Current Employment Status" value={a.employment_status}/>{a.employment_status === "Employed" ? <><Row label="Current Employer" value={a.current_employer}/><Row label="Current Designation" value={a.current_designation}/></> : null}<Row label="Expected Salary" value={a.expected_salary}/><Row label="Currency" value={a.expected_salary ? a.salary_currency : null}/><Row label="Introduction / Reason for Applying" value={a.introduction}/></dl></section>
      <section className={hrCard}><h2 className="text-xl font-bold">Education</h2>{state.education.map((row: any, index: number) => { const document = documentFor("education_certificate", row.id); return <article key={row.id} className="mt-4 border-t pt-4"><h3 className="font-bold">Education #{index + 1}</h3><dl className="mt-3 grid gap-4 md:grid-cols-3"><Row label="Degree / Certificate" value={row.degree}/><Row label="Institution" value={row.institution}/><Row label="Subject / Group / Major" value={row.subject}/><Row label="Result / Grade / CGPA" value={row.result}/><Row label="Completion Year" value={row.completion_year}/></dl><div className="mt-3">{document ? <DocumentActions document={document}/> : <span>Certificate: Not Provided</span>}</div></article>})}</section>
      <section className={hrCard}><h2 className="text-xl font-bold">Work Experience</h2>{!a.has_experience ? <p className="mt-3">Applicant declared no previous work experience.</p> : state.experience.map((row: any, index: number) => { const document = documentFor("experience_certificate", row.id); return <article key={row.id} className="mt-4 border-t pt-4"><h3 className="font-bold">Experience #{index + 1}</h3><dl className="mt-3 grid gap-4 md:grid-cols-3"><Row label="Company / Organization" value={row.company}/><Row label="Designation" value={row.designation}/><Row label="From" value={row.from_date}/><Row label="To" value={row.currently_working ? "Currently Working Here" : row.to_date}/><Row label="Responsibilities / Experience Summary" value={row.responsibilities}/></dl><div className="mt-3">{document ? <DocumentActions document={document}/> : <span>Experience Certificate: Not Provided</span>}</div></article>})}</section>
      <section className={hrCard}><h2 className="text-xl font-bold">Professional Qualification / Training</h2>{!a.has_qualification ? <p className="mt-3">No professional qualification/training declared.</p> : state.qualifications.map((row: any, index: number) => { const document = documentFor("qualification_certificate", row.id); return <article key={row.id} className="mt-4 border-t pt-4"><h3 className="font-bold">Qualification #{index + 1}</h3><dl className="mt-3 grid gap-4 md:grid-cols-3"><Row label="Qualification / Training Name" value={row.qualification_name}/><Row label="Institution / Issuer" value={row.institution}/><Row label="Subject / Area" value={row.subject}/><Row label="Completion Year" value={row.completion_year}/><Row label="Additional Details" value={row.details}/></dl><div className="mt-3">{document ? <DocumentActions document={document}/> : <span>Certificate: Not Provided</span>}</div></article>})}</section>
      <section className={hrCard}><h2 className="text-xl font-bold">Skills</h2>{state.skills.length ? <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-2">Skill</th><th>Proficiency</th><th>Details</th></tr></thead><tbody>{state.skills.map((row: any) => <tr key={row.id} className="border-t"><td className="py-2">{shown(row.skill_name)}</td><td>{shown(row.proficiency)}</td><td>{shown(row.details)}</td></tr>)}</tbody></table></div> : <p className="mt-3">No skills added.</p>}</section>
      <section className={hrCard}><h2 className="text-xl font-bold">Document Center</h2>{docs.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr><th className="py-2">Document</th><th>Context</th><th>File</th><th>Access</th></tr></thead><tbody>{docs.map((document: any) => { const educationIndex = state.education.findIndex((row: any) => row.id === document.related_record_id); const experience = state.experience.find((row: any) => row.id === document.related_record_id); const qualification = state.qualifications.find((row: any) => row.id === document.related_record_id); const context = educationIndex >= 0 ? `Education #${educationIndex + 1}` : experience ? experience.company : qualification ? qualification.qualification_name : "Application"; return <tr key={document.id} className="border-t"><td className="py-3 font-semibold">{documentLabel[document.document_type] ?? document.title}</td><td>{context}</td><td>{document.original_name}</td><td><DocumentActions document={document}/></td></tr>})}</tbody></table></div> : <p className="mt-3">No documents uploaded.</p>}</section>
    </div>
  </HrPage>;
}
