import { connection } from "next/server";
import { EmployeeHrShell } from "@/components/hr/EmployeeHrShell";
import { HrProgressBar } from "@/components/hr/HrProgressBar";
import { HrStatusBadge } from "@/components/hr/HrStatusBadge";
import { routes } from "@/lib/constants/routes";
import { leaveApplicationStatus, leaveApplicationStatusLabel } from "@/lib/hr/leave";
import { getEmployeeHrWorkspace } from "@/lib/hr/self-service";

export const dynamic = "force-dynamic";

export default async function EmployeeLeavePage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  const [data,params] = await Promise.all([getEmployeeHrWorkspace(),searchParams]);
  return <EmployeeHrShell title="My leave" subtitle="Review balances and requests or submit a new request." success={params.success} error={params.error}>
    <div className="mb-4 flex justify-end"><a href={routes.employeeHrNewLeave} className="rounded-lg bg-[var(--primary)] px-4 py-2 font-semibold text-[var(--primary-foreground)]">Request leave</a></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.leaveBalances.map((balance)=>{const type=Array.isArray(balance.hr_leave_types)?balance.hr_leave_types[0]:balance.hr_leave_types;const entitled=Number(balance.allocated_days)+Number(balance.adjusted_days);const used=Number(balance.used_days);const remaining=Math.max(0,entitled-used);return <article key={balance.id} className="rounded-2xl border bg-[var(--surface)] p-4 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{type?.name??"Leave"}</p><p className="text-xs text-[var(--muted-text)]">{balance.leave_year}</p></div><HrStatusBadge label={remaining?"Available":"Used"} tone={remaining?"success":"neutral"}/></div><dl className="mt-4 grid grid-cols-3 gap-2 text-center"><div><dt className="text-xs text-[var(--muted-text)]">Entitled</dt><dd className="font-bold">{entitled}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Used</dt><dd className="font-bold">{used}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Remaining</dt><dd className="font-bold text-emerald-700">{remaining}</dd></div></dl><div className="mt-4"><HrProgressBar label="Used" value={used} max={entitled} detail={`${used} of ${entitled} days`} tone={remaining?"warning":"neutral"}/></div></article>})}</section>
    <section className="mt-5 overflow-x-auto rounded-2xl border bg-[var(--surface)] shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[var(--muted-surface)]"><tr><th className="p-3">Application No</th><th>Leave Type</th><th>From / To</th><th>Total Days</th><th>Signed Copy</th><th>Application Status</th><th>View / Print</th></tr></thead><tbody>{data.leaveRequests.map((request)=>{const type=Array.isArray(request.hr_leave_types)?request.hr_leave_types[0]:request.hr_leave_types;const status=leaveApplicationStatus(request.status,request.signed_uploaded_at);return <tr key={request.id} className="border-t"><td className="p-3 font-semibold">{request.application_number}</td><td>{type?.name??"Leave"}</td><td>{request.start_date} – {request.end_date}</td><td>{request.requested_days}</td><td>{request.signed_uploaded_at?<a className="font-semibold text-blue-700" href={`/hr/leaves/${request.id}/signed-copy`} target="_blank">View signed copy</a>:request.status==="pending"?<a className="font-semibold text-emerald-700" href={`/employee/hr/leaves/${request.id}#signed-copy-upload`}>Upload Signed Copy</a>:"Not uploaded"}</td><td><HrStatusBadge status={status.toLowerCase()} label={leaveApplicationStatusLabel(status)}/></td><td><a className="font-semibold text-blue-700" href={`/employee/hr/leaves/${request.id}`}>View / Print</a></td></tr>})}</tbody></table>{!data.leaveRequests.length?<p className="p-8 text-center text-[var(--muted-text)]">No leave applications generated.</p>:null}</section>
  </EmployeeHrShell>;
}
