"use client";
import type { RoutePoint } from "@/lib/orders/types";

function project(points: RoutePoint[]) {
  if (!points.length) return [];
  const lats = points.map((p) => p.latitude), lngs = points.map((p) => p.longitude), minLat = Math.min(...lats), maxLat = Math.max(...lats), minLng = Math.min(...lngs), maxLng = Math.max(...lngs);
  return points.map((point) => ({ ...point, x: 8 + ((point.longitude - minLng) / Math.max(maxLng - minLng, .01)) * 84, y: 86 - ((point.latitude - minLat) / Math.max(maxLat - minLat, .01)) * 72 }));
}

export function AnimatedShipmentMap({ points, latestLabel, transportMode, delivered = false }: { points: RoutePoint[]; latestLabel?: string | null; transportMode: string; delivered?: boolean }) {
  const plotted = project(points), path = plotted.map((point, index) => `${index ? "L" : "M"} ${point.x} ${point.y}`).join(" ");
  if (plotted.length < 2) return <section className="rounded-2xl border bg-[var(--surface)] p-5"><h3 className="font-semibold">Estimated logistics map</h3><p className="mt-3 text-sm text-[var(--muted-text)]">Route coordinates are not available yet. Tracking will appear as recorded locations are added.</p></section>;
  return <section className="overflow-hidden rounded-2xl border bg-gradient-to-br from-sky-50 via-white to-cyan-50 p-5 text-slate-950"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-sky-700">Estimated route · not live GPS</p><h3 className="mt-1 text-lg font-semibold">{transportMode.replaceAll("_", " ")} logistics journey</h3></div><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold shadow-sm">{delivered ? "Delivered" : latestLabel ? `Latest recorded: ${latestLabel}` : "Awaiting recorded update"}</span></div><svg viewBox="0 0 100 100" role="img" aria-label="Estimated shipment route" className="mt-4 h-64 w-full rounded-xl bg-[radial-gradient(circle_at_20%_20%,#dbeafe_0,transparent_30%),linear-gradient(135deg,#eff6ff,#ecfeff)]"><defs><filter id="glow"><feGaussianBlur stdDeviation="1.4" result="coloredBlur"/><feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d={path} fill="none" stroke="#0ea5e9" strokeWidth="1.8" strokeDasharray="4 3" className="shipment-route-line"/><path d={path} fill="none" stroke="#0369a1" strokeWidth=".45" opacity=".45"/>{plotted.map((point, index) => <g key={`${point.label}-${index}`}><circle cx={point.x} cy={point.y} r={index === plotted.length - 1 ? 2.1 : 1.4} fill={index === plotted.length - 1 ? "#0f766e" : "#fff"} stroke="#0369a1" strokeWidth=".7" filter="url(#glow)"/><text x={point.x} y={point.y + (index % 2 ? 5 : -3)} textAnchor="middle" fontSize="3.2" fontWeight="600" fill="#0f172a">{point.label.slice(0, 22)}</text></g>)}{!delivered ? <circle r="1.8" fill="#f97316" filter="url(#glow)" className="shipment-marker"><animateMotion dur="7s" repeatCount="indefinite" path={path}/></circle> : null}</svg><p className="mt-3 text-xs text-slate-600">Route geometry is an operational estimate based on staff-entered checkpoints. Map-style rendering uses no paid API. Geographic data attribution: OpenStreetMap contributors.</p></section>;
}
