/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useEffect, useRef, useState } from "react";
import { allocateSerialsAction } from "@/app/admin/orders/actions";

type SerialResult = { id: string; sen_serial: string; manufacturer_serial: string | null; status: string; condition: string; warehouse_name: string | null; location_name: string | null; exact: boolean };
export function SerialAllocator({ orderId, orderItemId, requiredCount, currentCount }: { orderId: string; orderItemId: string; requiredCount: number; currentCount: number }) {
  const [query, setQuery] = useState(""), [results, setResults] = useState<SerialResult[]>([]), [selected, setSelected] = useState<string[]>([]), [message, setMessage] = useState(""), timer = useRef<ReturnType<typeof setTimeout> | null>(null), video = useRef<HTMLVideoElement>(null);
  useEffect(() => { if (timer.current) clearTimeout(timer.current); if (query.trim().length < 2) { setResults([]); return; } timer.current = setTimeout(async () => { const response = await fetch(`/api/admin/order-serial-search?q=${encodeURIComponent(query)}&orderItemId=${orderItemId}`, { cache: "no-store" }); const body = await response.json(); setResults(body.results ?? []); setMessage(body.error ?? ""); }, 250); return () => { if (timer.current) clearTimeout(timer.current); }; }, [query, orderItemId]);
  async function scan() { const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => { detect(source: ImageBitmapSource): Promise<Array<{ rawValue: string }>> } }).BarcodeDetector; if (!Detector || !navigator.mediaDevices?.getUserMedia) { setMessage("Camera scanning is unavailable. Use a keyboard scanner or type the serial."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); if (!video.current) return; video.current.srcObject = stream; await video.current.play(); const detector = new Detector({ formats: ["qr_code", "code_128"] }); for (let i = 0; i < 80; i++) { const match = (await detector.detect(video.current))[0]; if (match?.rawValue) { setQuery(match.rawValue.replace(/^SEN:1:/, "")); setMessage("Code detected. Confirm the matching unit below."); break; } await new Promise((resolve) => setTimeout(resolve, 150)); } stream.getTracks().forEach((track) => track.stop()); } catch { setMessage("Camera permission was denied. Manual input remains available."); } }
  const remaining = Math.max(0, requiredCount - currentCount), toggle = (id: string) => setSelected((value) => value.includes(id) ? value.filter((item) => item !== id) : value.length < remaining ? [...value, id] : value);
  return <form action={allocateSerialsAction.bind(null, orderId, orderItemId)} className="rounded-2xl border bg-[var(--surface)] p-5"><input type="hidden" name="method" value="scan"/><div className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1 text-sm font-semibold">SEN or manufacturer serial<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Type or scan at least 2 characters" className="mt-1 w-full rounded-xl border px-4 py-3"/></label><button type="button" onClick={scan} className="rounded-xl border px-4 py-3 font-semibold">Scan barcode / QR</button></div><video ref={video} muted playsInline className="mt-3 hidden max-h-56 w-full rounded-xl bg-black"/><p aria-live="polite" className="mt-2 text-sm text-[var(--muted-text)]">Need {remaining} more · Selected {selected.length}. {message}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{results.map((serial) => <label key={serial.id} className={`cursor-pointer rounded-xl border p-4 ${selected.includes(serial.id) ? "border-[var(--primary)] bg-blue-50" : ""}`}><input type="checkbox" name="serial_id" value={serial.id} checked={selected.includes(serial.id)} onChange={() => toggle(serial.id)} className="mr-3"/><b>{serial.sen_serial}</b>{serial.exact ? <span className="ml-2 rounded bg-green-100 px-2 py-1 text-xs text-green-800">Exact match</span> : null}<p className="mt-1 text-sm">Manufacturer: {serial.manufacturer_serial || "—"}</p><p className="text-xs text-[var(--muted-text)]">{serial.condition} · {serial.warehouse_name || "Warehouse"}{serial.location_name ? ` / ${serial.location_name}` : ""}</p></label>)}</div><button disabled={!remaining || selected.length !== remaining} className="mt-4 rounded-xl bg-[var(--primary)] px-5 py-3 font-semibold text-[var(--primary-foreground)] disabled:cursor-not-allowed disabled:opacity-40">Allocate exactly {remaining} unit(s)</button></form>;
}
