import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { dirname,join } from "node:path";
import { MAX_RECRUITMENT_FILE_BYTES,recruitmentApplicationNumberIsValid,validateRecruitmentDraft,validateRecruitmentFile,type RecruitmentDraft } from "../lib/hr/recruitment-job-application.ts";

const root=join(dirname(fileURLToPath(import.meta.url)),"..");
const migration=readFileSync(join(root,"supabase/migrations/202609280001_hr_recruitment_job_application_v1.sql"),"utf8");
const submitRpcFix=readFileSync(join(root,"supabase/migrations/202609280002_hr_recruitment_job_application_submit_rpc_fix.sql"),"utf8");
const actions=readFileSync(join(root,"app/employee/hr/recruitment/application/actions.ts"),"utf8");
const access=readFileSync(join(root,"lib/hr/recruitment-job-application-data.ts"),"utf8");
const route=readFileSync(join(root,"app/employee/hr/recruitment/application/documents/[documentId]/route.ts"),"utf8");
const terms=readFileSync(join(root,"lib/hr/recruitment-terms.ts"),"utf8");
const base:RecruitmentDraft={fullName:"Applicant",fatherName:"Father",motherName:"Mother",dateOfBirth:"1990-01-01",gender:"Male",maritalStatus:"Single",nationality:"Bangladeshi",phone:"01700000000",email:"employee@example.com",presentAddress:"Present",permanentAddress:"Permanent",emergencyContactName:"Emergency",emergencyContactPhone:"01800000000",emergencyContactRelationship:"Sibling",spouseName:"",spouseContactNumber:"",nidNumber:"123",passportNumber:"",passportExpiryDate:"",positionAppliedFor:"Engineer",joiningDate:"2026-10-01",employmentStatus:"Unemployed",currentEmployer:"",currentDesignation:"",expectedSalary:"",salaryCurrency:"BDT",introduction:"A".repeat(120),hasExperience:false,hasQualification:false,education:[{id:"11111111-1111-4111-8111-111111111111",degree:"BSc",institution:"University",subject:"Engineering",result:"",completionYear:"2020"}],experience:[],qualifications:[],skills:[]};
const docs=()=>new Set(["photograph","cv","nid_copy",`education_certificate:${base.education[0].id}`]);
const errors=(patch:Partial<RecruitmentDraft>={},documents=docs())=>validateRecruitmentDraft({...base,...patch},true,documents);

test("permission required server-side",()=>assert.match(access,/requireEmployeeRecruitmentAccess/));
test("Terms 9\/9 required before application",()=>assert.match(access,/terms_completed[\s\S]*current_step !== 9/));
test("customer and unauthenticated users are denied by employee permission guard",()=>assert.match(access,/requireEmployeeRecruitmentAccess/));
test("employee application reads are ownership-scoped",()=>assert.match(access,/eq\("profile_id",context\.profile\.id\)/));
test("one application per employee is enforced",()=>assert.match(migration,/unique\(profile_id\)/));
test("incomplete draft may save",()=>assert.deepEqual(validateRecruitmentDraft({...base,fullName:"",education:[]},false),{}));
test("draft persistence uses server database",()=>assert.match(actions,/hr_recruitment_job_applications/));
test("required personal fields enforced",()=>assert.ok(errors({fullName:""}).fullName));
test("married requires spouse name",()=>assert.ok(errors({maritalStatus:"Married"}).spouseName));
test("married requires spouse contact",()=>assert.ok(errors({maritalStatus:"Married"}).spouseContactNumber));
test("valid email required",()=>assert.ok(errors({email:"bad"}).email));
test("future date of birth rejected",()=>assert.ok(errors({dateOfBirth:"2999-01-01"}).dateOfBirth));
test("NID number required",()=>assert.ok(errors({nidNumber:""}).nidNumber));
test("NID document required",()=>{const d=docs();d.delete("nid_copy");assert.ok(errors({},d).nidCopy)});
test("passport is optional",()=>assert.equal(errors().passportExpiryDate,undefined));
test("passport number requires expiry",()=>assert.ok(errors({passportNumber:"P123"}).passportExpiryDate));
test("passport number requires copy",()=>assert.ok(errors({passportNumber:"P123",passportExpiryDate:"2030-01-01"}).passportCopy));
test("photograph required",()=>{const d=docs();d.delete("photograph");assert.ok(errors({},d).photograph)});
test("photograph is image-only",()=>assert.ok(validateRecruitmentFile({size:100,type:"application/pdf"},true)));
test("CV required",()=>{const d=docs();d.delete("cv");assert.ok(errors({},d).cv)});
test("education required",()=>assert.ok(errors({education:[]}).education));
test("education certificate required per row",()=>{const d=docs();d.delete(`education_certificate:${base.education[0].id}`);assert.ok(errors({},d)["education.0.certificate"])});
test("experience NO allows zero rows",()=>assert.equal(errors({hasExperience:false,experience:[]}).experience,undefined));
test("experience YES requires a row",()=>assert.ok(errors({hasExperience:true,experience:[]}).experience));
test("experience certificate optional",()=>assert.deepEqual(errors({hasExperience:true,experience:[{id:"22222222-2222-4222-8222-222222222222",company:"SEN",designation:"Engineer",fromDate:"2020-01-01",toDate:"2021-01-01",currentlyWorking:false,responsibilities:"Work"}]}),{}));
test("qualification NO allows zero rows",()=>assert.equal(errors({hasQualification:false,qualifications:[]}).qualifications,undefined));
test("qualification YES requires a row",()=>assert.ok(errors({hasQualification:true,qualifications:[]}).qualifications));
test("qualification certificate optional",()=>assert.deepEqual(errors({hasQualification:true,qualifications:[{id:"33333333-3333-4333-8333-333333333333",name:"Training",institution:"Institute",subject:"",completionYear:"2024",details:""}]}),{}));
test("zero skills allowed",()=>assert.deepEqual(errors({skills:[]}),{}));
test("malformed skill row rejected",()=>assert.ok(errors({skills:[{id:"44444444-4444-4444-8444-444444444444",name:"",proficiency:"",details:""}]})["skills.0.name"]));
test("file maximum is 10MB",()=>assert.equal(MAX_RECRUITMENT_FILE_BYTES,10*1024*1024));
test("oversize file rejected",()=>assert.ok(validateRecruitmentFile({size:MAX_RECRUITMENT_FILE_BYTES+1,type:"application/pdf"})));
test("invalid file type rejected",()=>assert.ok(validateRecruitmentFile({size:100,type:"application/javascript"})));
test("own document route scopes profile",()=>assert.match(route,/eq\("profile_id",context\.profile\.id\)/));
test("cross-employee document access denied",()=>assert.match(route,/Document not found/));
test("final checkbox required server-side",()=>assert.match(actions,/information_confirmed[\s\S]*Final confirmation is required/));
test("application number format",()=>{assert.ok(recruitmentApplicationNumberIsValid("JOB-2026-0001"));assert.ok(!recruitmentApplicationNumberIsValid("JOB-26-1"))});
test("application number is unique and atomic",()=>{assert.match(migration,/application_number text unique/);assert.match(migration,/on conflict\(application_year\) do update/)});
test("submission RPC qualifies the application year variable",()=>{assert.match(submitRpcFix,/v_application_year integer/);assert.match(submitRpcFix,/values\(v_application_year,1\)/);assert.doesNotMatch(submitRpcFix,/values\(application_year,1\)/)});
test("submitted application is locked server-side",()=>{assert.match(actions,/status===\"SUBMITTED\"/);assert.match(actions,/eq\("status",\"DRAFT\"\)/)});
test("submitted document mutation denied by draft-only save",()=>assert.match(actions,/A submitted application is locked/));
test("private bucket and ownership storage policy",()=>{assert.match(migration,/hr-recruitment-documents','hr-recruitment-documents',false/);assert.match(migration,/storage\.foldername\(name\)\)\[1\]=auth\.uid/)});
test("Terms V2 remains exactly nine with 49 ইনশাআল্লাহ occurrences",()=>{assert.match(terms,/SEN-RECRUITMENT-LITE-V2/);assert.equal((terms.match(/ইনশাআল্লাহ/g)??[]).length,49);assert.match(terms,/Total Steps:\\n9/)});
test("migration is Recruitment-only",()=>assert.doesNotMatch(migration,/\b(sales|cashbook|inventory|attendance|leave_requests|customers|orders|payroll)\b/i));
