export const permissionDestinations: Record<string, string> = {
  "activity.view_own": "/employee/activity",
  "employees.view": "/employee/employees",
  "employees.view_detail": "/employee/employees",
  "employees.edit_profile": "/employee/employees",
  "employees.view_permissions": "/employee/employees",
  "employees.manage_permissions": "/employee/employees",
  "employees.view_activity": "/employee/employees",
  "crm.create": "/admin/crm/leads/new",
  "crm.export": "/admin/crm/export",
  "products.view": "/admin/products",
  "products.create": "/admin/products/new",
  "products.import": "/admin/products/import",
  "orders.view": "/admin/orders",
  "orders.create": "/admin/orders/new",
  "sales.view": "/admin/sales",
  "sales.view_all": "/admin/sales",
  "sales.view_own": "/admin/sales",
  "sales.create": "/admin/sales/new",
  "quotations.view": "/admin/quotations",
  "quotations.view_all": "/admin/quotations",
  "quotations.create": "/admin/quotations/new",
  "inventory.view": "/admin/inventory",
  "inventory.adjust_stock": "/admin/inventory/adjustments/new",
  "inventory.transfer": "/admin/inventory/adjustments/new",
  "inventory.receive": "/admin/serials/generate",
  "inventory.receive_new_stock": "/employee/inventory/receive",
  "inventory.export": "/admin/inventory/export",
  "warehouses.view": "/admin/warehouses",
  "locations.view": "/admin/work-locations",
  "tracking_statuses.view": "/admin/tracking-statuses",
  "serials.view": "/admin/serials",
  "serials.generate": "/admin/serials/generate",
  "serials.scan": "/admin/serials/scan",
  "serials.print": "/admin/serials/print",
  "serials.regenerate": "/admin/serials/regenerate",
  "serials.export": "/admin/serials/export",
  "shipments.view": "/admin/shipments",
  "purchasing.view": "/admin/purchasing",
  "purchasing.create": "/admin/purchasing/new",
  "purchasing.export": "/admin/purchasing/export",
  "suppliers.view": "/admin/suppliers",
  "accounting.view": "/admin/accounting",
  "accounting.manage_cashbook": "/admin/accounting",
  "support.view": "/admin/messages",
  "hr.view": "/admin/hr",
  "hr.view_attendance": "/admin/hr/attendance",
  "hr.manage_attendance": "/admin/hr/attendance",
  "hr.view_leave": "/admin/hr/leaves",
  "hr.manage_leave": "/admin/hr/leaves",
  "hr.view_payroll": "/admin/hr/payroll",
  "hr.manage_payroll": "/admin/hr/payroll",
  "hr.manage_employees": "/admin/hr/employees",
};

export function destinationForPermission(permissionKey:string){
  return permissionDestinations[permissionKey]??null;
}
