import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission, getPermissionMatrix, getPermissionCatalogue } from "@/lib/auth/permissions";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { ActivityTable, type ActivityRow } from "@/components/activity/ActivityTable";
import { routes } from "@/lib/constants/routes";

export default async function EmployeePage(){
  const {profile}=await requirePermission("dashboard.view");
  const [matrix,modules]=await Promise.all([getPermissionMatrix(profile.id),getPermissionCatalogue()]);
  const permittedModules=modules.filter((module)=>module.permissions.some((permission)=>matrix.effectiveKeys.includes(permission.key)));
  const supabase=createSupabaseAdminClient();
  const {data:activity}=await supabase.from("audit_logs").select("id,actor_id,action,module,entity_type,entity_id,description,old_values,new_values,created_at").eq("actor_id",profile.id).order("created_at",{ascending:false}).limit(5);
  return <DashboardShell employeePermissions={matrix.effectiveKeys} title="Employee Workspace" subtitle={`Welcome ${profile.full_name??profile.email??"employee"}. Your access is controlled by your assigned SEN permissions.`}><section className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border bg-[var(--surface)] p-6"><p className="text-sm text-[var(--muted-text)]">Role and status</p><p className="mt-2 font-semibold">{profile.role} · {profile.status}</p></article><article className="rounded-xl border bg-[var(--surface)] p-6"><p className="text-sm text-[var(--muted-text)]">Permission template</p><p className="mt-2 font-semibold">{matrix.template?.name??"No active template"}</p></article><article className="rounded-xl border bg-[var(--surface)] p-6"><p className="text-sm text-[var(--muted-text)]">Effective permissions</p><p className="mt-2 text-3xl font-bold">{matrix.effectiveKeys.length}</p></article></section><section className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Permitted modules</h2>{permittedModules.length?<div className="mt-4 grid gap-3 md:grid-cols-3">{permittedModules.map((module)=><article key={module.id} className="rounded border p-4"><h3 className="font-semibold">{module.name}</h3><p className="mt-1 text-sm text-[var(--muted-text)]">{module.is_implemented?"Available foundation":"Permission reserved for a future module"}</p></article>)}</div>:<p className="mt-3 text-[var(--muted-text)]">No employee modules are currently permitted.</p>}</section><section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Recent activity</h2>{matrix.effectiveKeys.includes("activity.view_own")?<a href={routes.employeeActivity} className="font-semibold">View all</a>:null}</div><ActivityTable rows={(activity??[]) as ActivityRow[]} people={{[profile.id]:{name:profile.full_name??profile.email??"You",email:profile.email}}}/></section></DashboardShell>;
}
