import { connection } from "next/server";
import { HrPage, hrCard, hrField, hrPrimary, relation } from "@/components/hr/HrPage";
import { getHrEmployees, getHrPerformance } from "@/lib/hr/operational";
import { savePerformanceAction } from "../hr-actions";

export const dynamic = "force-dynamic";

export default async function PerformancePage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  const [data, employees, params] = await Promise.all([getHrPerformance(),getHrEmployees({pageSize:100,status:"all"}),searchParams]);
  const employeeSelect = <><option value="">Select employee</option>{employees.rows.map(e=><option key={e.id} value={e.id}>{relation(e.profiles)?.full_name||e.employee_number}</option>)}</>;
  return <HrPage title="Performance" subtitle="Record reviews and goals while preserving employee history." success={params.success} error={params.error}>
    <section className="grid gap-4 xl:grid-cols-2"><form action={savePerformanceAction} className={hrCard}><input type="hidden" name="kind" value="review"/><input type="hidden" name="return_to" value="/admin/hr/performance"/><h2 className="font-semibold">New performance review</h2><label className="mt-3 block text-sm font-semibold">Employee<select name="employee_record_id" required className={hrField}>{employeeSelect}</select></label><div className="mt-3 grid grid-cols-3 gap-3"><label className="text-sm font-semibold">From<input type="date" name="period_start" required className={hrField}/></label><label className="text-sm font-semibold">To<input type="date" name="period_end" required className={hrField}/></label><label className="text-sm font-semibold">Rating / 5<input type="number" min="0" max="5" step=".1" name="rating" required className={hrField}/></label></div>{[["strengths","Strengths"],["improvements","Areas to improve"],["summary","Summary"]].map(([name,label])=><label key={name} className="mt-3 block text-sm font-semibold">{label}<textarea name={name} className={hrField}/></label>)}<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="finalized"/> Finalize and show to employee</label><button className={`${hrPrimary} mt-3`}>Save review</button></form>
      <form action={savePerformanceAction} className={hrCard}><input type="hidden" name="kind" value="goal"/><input type="hidden" name="return_to" value="/admin/hr/performance"/><h2 className="font-semibold">New employee goal</h2><label className="mt-3 block text-sm font-semibold">Employee<select name="employee_record_id" required className={hrField}>{employeeSelect}</select></label><label className="mt-3 block text-sm font-semibold">Goal title<input name="title" required className={hrField}/></label><label className="mt-3 block text-sm font-semibold">Description<textarea name="description" className={hrField}/></label><label className="mt-3 block text-sm font-semibold">Target date<input type="date" name="target_date" className={hrField}/></label><button className={`${hrPrimary} mt-3`}>Create goal</button></form></section>
    <section className="mt-5 grid gap-4 xl:grid-cols-2"><article className={hrCard}><h2 className="font-semibold">Reviews</h2>{data.reviews.map(r=>{const e=relation(r.hr_employee_records);return <p key={r.id} className="border-t py-3 text-sm"><strong>{relation(e?.profiles)?.full_name||e?.employee_number}</strong> · {r.rating}/5 · {r.status}</p>})}</article><article className={hrCard}><h2 className="font-semibold">Goals</h2>{data.goals.map(g=>{const e=relation(g.hr_employee_records);return <p key={g.id} className="border-t py-3 text-sm"><strong>{relation(e?.profiles)?.full_name||e?.employee_number}</strong> · {g.title} · {g.progress_percent}%</p>})}</article></section>
  </HrPage>;
}
