import type { getProductOptions } from "@/lib/inventory/products";
import { RichTextEditor } from "@/components/inventory/RichTextEditor";
import { ProductIdentityFields } from "@/components/inventory/ProductIdentityFields";
type Options=Awaited<ReturnType<typeof getProductOptions>>; type Product=Record<string,unknown>;
const input="mt-1 w-full rounded border p-3";
export function ProductForm({action,options,product}:{action:(formData:FormData)=>void|Promise<void>;options:Options;product?:Product}){
 const value=(key:string,fallback="")=>String(product?.[key]??fallback);
 return <form action={action} className="space-y-6" encType="multipart/form-data">
  <section className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">General</h2><div className="mt-4 grid gap-4 md:grid-cols-2">
   <label>Name<input name="name" required defaultValue={value("name")} className={input}/></label><label>Slug<input name="slug" defaultValue={value("slug")} className={input}/></label>
   <ProductIdentityFields brands={options.brands} productId={value("id")||undefined} initialBrandId={value("brand_id")} initialModel={value("model_number")} initialSku={value("sku")}/>
   <label>Product type<select name="product_type" defaultValue={value("product_type","simple")} className={input}><option value="simple">Simple product</option><option value="variable">Variable product</option></select></label>
   <label>Status<select name="status" defaultValue={value("status","draft")} className={input}><option value="draft">Draft</option><option value="active">Active / published</option><option value="archived">Archived</option></select></label>
   <label>SEN business category<select name="sen_business_category" defaultValue={value("sen_business_category","Others")} className={input}>{["Networking","Energy","Medical Equipment","Others"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Category<select name="category_id" defaultValue={value("category_id")} className={input}><option value="">Uncategorized</option>{options.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   <label>Barcode<input name="barcode" defaultValue={value("barcode")} className={input}/></label><label>Manufacturer part number<input name="manufacturer_part_number" defaultValue={value("manufacturer_part_number")} className={input}/></label>
  </div><RichTextEditor name="short_description" label="Short description" defaultValue={value("short_description")} maxLength={4000}/><RichTextEditor name="description" label="Full description" defaultValue={value("description")} maxLength={20000}/></section>
  <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Pricing</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label>Purchase cost<input type="number" step="0.0001" min="0" name="purchase_cost" defaultValue={value("purchase_cost")} className={input}/></label><label>Regular price<input type="number" step="0.0001" min="0" name="regular_price" defaultValue={value("regular_price")} className={input}/></label><label>Sale price<input type="number" step="0.0001" min="0" name="sale_price" defaultValue={value("sale_price")} className={input}/></label><label>Currency<input name="currency" maxLength={3} defaultValue={value("currency","USD")} className={`${input} uppercase`}/></label></div></div>
   <div className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Inventory</h2><div className="mt-4 grid gap-4"><label>Stock status<select name="stock_status" defaultValue={value("stock_status","in_stock")} className={input}><option value="in_stock">In stock</option><option value="out_of_stock">Out of stock</option><option value="on_backorder">On backorder</option></select></label><label>Low-stock threshold<input type="number" step="0.0001" min="0" name="low_stock_threshold" defaultValue={value("low_stock_threshold","0")} className={input}/></label>{[["manage_stock","Manage stock"],["allow_backorders","Allow backorders"],["sold_individually","Sold individually"],["serial_tracking_required","Serial tracking required"],["batch_tracking_enabled","Batch/lot tracking"]].map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" name={key} defaultChecked={Boolean(product?.[key]??(key==="manage_stock"))}/>{label}</label>)}</div></div></section>
  <section className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Shipping, warranty and advanced</h2><div className="mt-4 grid gap-4 md:grid-cols-4">{["weight","length","width","height"].map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input type="number" min="0" step="0.0001" name={key} defaultValue={value(key)} className={input}/></label>)}</div><div className="mt-4 grid gap-4 md:grid-cols-2"><label>Country of origin<input name="country_of_origin" defaultValue={value("country_of_origin")} className={input}/></label><label>Warranty information<input name="warranty_information" defaultValue={value("warranty_information")} className={input}/></label></div><label className="mt-4 block">Specifications JSON<textarea name="specifications" defaultValue={value("specifications","{}")} className="mt-1 min-h-24 w-full rounded border p-3 font-mono text-sm"/></label><label className="mt-4 block">Internal notes<textarea name="internal_notes" defaultValue={value("internal_notes")} className="mt-1 min-h-24 w-full rounded border p-3"/></label><div className="mt-4 flex flex-wrap gap-4"><label><input type="checkbox" name="featured" defaultChecked={Boolean(product?.featured)}/> Featured</label><label><input type="checkbox" name="public_catalogue_visible" defaultChecked={Boolean(product?.public_catalogue_visible)}/> Public catalogue visibility</label></div></section>
  <section className="rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Product Images</h2><p className="mt-1 text-sm text-[var(--muted-text)]">JPG, PNG or WebP, maximum 10 MB each. Images upload after the product is safely saved.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label>Main product image<input type="file" name="main_image" accept="image/jpeg,image/png,image/webp" className={input}/></label><label>Gallery images<input type="file" name="gallery_images" multiple accept="image/jpeg,image/png,image/webp" className={input}/></label><label className="md:col-span-2">Image alt text<input name="image_alt_text" maxLength={200} className={input}/></label></div></section>
  <div className="flex flex-wrap gap-3"><button name="submit_intent" value="save" className="min-h-12 rounded bg-[var(--primary)] px-6 py-3 font-semibold text-[var(--primary-foreground)]">Save product</button><button name="submit_intent" value="save_generate" className="min-h-12 rounded border px-6 py-3 font-semibold">Save and generate serials</button></div>
 </form>;
}
