"use client";
import { useEffect, useMemo, useState } from "react";
import { automaticSku } from "@/lib/inventory/identifiers";
type Brand={id:string;name:string}; type Match={id:string;name:string;sku:string;status:string;available:number;serialCount:number};
export function ProductIdentityFields({brands,productId,initialBrandId="",initialModel="",initialSku=""}:{brands:Brand[];productId?:string;initialBrandId?:string;initialModel?:string;initialSku?:string}){
 const[brandId,setBrandId]=useState(initialBrandId),[model,setModel]=useState(initialModel),[custom,setCustom]=useState(Boolean(productId)),[sku,setSku]=useState(initialSku),[matches,setMatches]=useState<Match[]>([]),[checking,setChecking]=useState(false);
 const brand=brands.find(x=>x.id===brandId)?.name??"",generated=useMemo(()=>automaticSku(brand,model),[brand,model]);
 useEffect(()=>{const key=setTimeout(async()=>{if(!brandId||model.trim().length<2){setMatches([]);return}setChecking(true);try{const q=new URLSearchParams({brand:brandId,model,exclude:productId??""}),response=await fetch(`/api/admin/product-identity?${q}`,{cache:"no-store"}),body=await response.json();setMatches(body.matches??[])}finally{setChecking(false)}},350);return()=>clearTimeout(key)},[brandId,model,productId]);
 const displayedSku=custom?sku:generated; const regenerate=()=>{if(productId&&!confirm("Regenerate this product SKU? Existing physical-unit serials will not change."))return;setCustom(false)};
 return <div className="md:col-span-2 grid gap-4 rounded-xl border border-blue-200 bg-blue-50/50 p-4 md:grid-cols-2">
  <label className="font-semibold">Brand <span className="text-red-600" aria-hidden="true">*</span><select name="brand_id" required value={brandId} onChange={e=>setBrandId(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-3 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200 invalid:border-red-400"><option value="">Choose a brand</option>{brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label className="font-semibold">Model number <span className="text-red-600" aria-hidden="true">*</span><input name="model_number" required value={model} onChange={e=>setModel(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200 invalid:border-red-400"/><span className="mt-1 block text-xs font-normal text-[var(--muted-text)]">Brand and model form the catalogue identity.</span></label>
  <label className="font-semibold">SKU <span className="text-red-600" aria-hidden="true">*</span><input name="sku" required readOnly={!custom} value={displayedSku} onChange={e=>setSku(e.target.value.toUpperCase())} className="mt-1 w-full rounded-lg border bg-white p-3 font-mono font-normal focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200 invalid:border-red-400"/><span className="mt-1 block text-xs font-normal text-[var(--muted-text)]">SKU generated from brand and model number.</span></label>
  <div className="flex flex-wrap items-end gap-2"><button type="button" onClick={()=>navigator.clipboard.writeText(displayedSku)} disabled={!displayedSku} className="rounded border bg-white px-3 py-2">Copy SKU</button><button type="button" onClick={regenerate} disabled={!generated} className="rounded border bg-white px-3 py-2">Regenerate SKU</button><label className="flex items-center gap-2 rounded border bg-white px-3 py-2"><input type="checkbox" name="custom_sku" checked={custom} onChange={e=>setCustom(e.target.checked)}/>Use custom SKU</label></div>
  {checking?<p className="md:col-span-2 text-sm">Checking existing catalogue…</p>:null}
  {matches.length?<div className="md:col-span-2 rounded-lg border border-amber-300 bg-amber-50 p-4"><strong>This product model already exists.</strong><p className="mt-1 text-sm">Open it and add stock instead of creating a duplicate.</p>{matches.map(item=><div key={item.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded border bg-white p-3"><div><b>{item.name}</b><span className="block text-sm">{item.sku} · {item.status} · {item.available} available · {item.serialCount} serials</span></div><div className="flex gap-2"><a href={`/admin/products/${item.id}`} className="rounded border px-3 py-2 font-semibold">Open product</a><a href={`/admin/products/${item.id}/stock/add`} className="rounded bg-[var(--primary)] px-3 py-2 font-semibold text-white">Add stock</a></div></div>)}</div>:null}
 </div>;
}
