export const routes = {
  home: "/",
  products: "/products",
  solutions: "/solutions",
  industries: "/industries",
  about: "/about",
  contact: "/contact",
  search: "/search",
  requestQuote: "/request-quote/general",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  logout: "/logout",
  profile: "/profile",
  account: "/account",
  employee: "/employee",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminPermissions: "/admin/permissions",
  adminActivity: "/admin/activity",
  adminOrders: "/admin/orders",
  adminSales: "/admin/sales",
  adminShipments: "/admin/shipments",
  adminPurchasing: "/admin/purchasing",
  adminSuppliers: "/admin/suppliers",
  adminSupplierCategories: "/admin/supplier-categories",
  adminAccounting: "/admin/accounting",
  adminHr: "/admin/hr",
  adminHrEmployees: "/admin/hr/employees",
  adminHrNewEmployee: "/admin/hr/employees/new",
  adminHrDepartments: "/admin/hr/departments",
  adminHrAttendance: "/admin/hr/attendance",
  adminHrAttendanceCorrections: "/admin/hr/attendance/corrections",
  adminHrLeaves: "/admin/hr/leaves",
  adminHrPayroll: "/admin/hr/payroll",
  adminHrPerformance: "/admin/hr/performance",
  adminHrReports: "/admin/hr/reports",
  adminHrSettings: "/admin/hr/settings",
  adminCrm: "/admin/crm",
  adminProducts: "/admin/products",
  adminCategories: "/admin/categories",
  adminBrands: "/admin/brands",
  adminAttributes: "/admin/attributes",
  adminInventory: "/admin/inventory",
  adminInventoryAdjustments: "/admin/inventory/adjustments",
  adminInventoryMovements: "/admin/inventory/movements",
  adminWarehouses: "/admin/warehouses",
  adminSerials: "/admin/serials",
  adminWorkLocations: "/admin/work-locations",
  adminTrackingStatuses: "/admin/tracking-statuses",
  employeeProfile: "/employee/profile",
  employeeActivity: "/employee/activity",
  employeeHr: "/employee/hr",
  employeeHrAttendance: "/employee/hr/attendance",
  employeeHrAttendanceCorrection: "/employee/hr/attendance/corrections/new",
  employeeHrLeaves: "/employee/hr/leaves",
  employeeHrNewLeave: "/employee/hr/leaves/new",
  accountAddresses: "/account/addresses",
  accountOrders: "/account/orders",
  accountSales: "/account/sales",
  accountProfile: "/profile",
  accountMessages: "/account/messages",
  accountQuotations: "/account/quotations",
  cart: "/cart",
  adminQuotations: "/admin/quotations",
  adminSupport: "/admin/messages",
  adminPaymentSettings: "/admin/settings/payments",
  adminDataManagement: "/admin/settings/data-management",
  adminArchive: "/admin/archive",
  environmentCheck: "/environment-check",
} as const;

export type AccountRole = "customer" | "employee" | "admin";
export type AccountStatus = "active" | "suspended" | "disabled";

export function dashboardPathForRole(role?: string | null) {
  if (role === "admin") return routes.admin;
  if (role === "employee") return routes.employee;
  return routes.account;
}
