/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import { connection } from "next/server";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { getProductList, getProductOptions, type ProductListParams } from "@/lib/inventory/products";
import { archiveProductAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<ProductListParams & { success?: string; error?: string }> }) {
  await connection();
  const { profile, permissions } = await requirePermission("products.view"), params = await searchParams;
  const [{ products, count, page, size }, options] = await Promise.all([getProductList(params), getProductOptions()]);
  const pages = Math.max(1, Math.ceil(count / size));
  return <DashboardShell admin={profile.role === "admin"} employeePermissions={profile.role === "employee" ? permissions : undefined} title="Products" subtitle="Manage SEN simple and variable products, classification, pricing and stock settings.">
    {params.success ? <p className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-green-900">{params.success}</p> : null}{params.error ? <p className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-red-900">{params.error}</p> : null}
    <div className="mb-5 flex flex-wrap gap-3"><a href="/admin/products/new" className="rounded bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)]">Add product</a><a href="/admin/categories" className="rounded border px-4 py-3 font-semibold">Categories</a><a href="/admin/brands" className="rounded border px-4 py-3 font-semibold">Brands</a><a href="/admin/attributes" className="rounded border px-4 py-3 font-semibold">Attributes</a><a href="/admin/inventory/export" className="rounded border px-4 py-3 font-semibold">Export inventory CSV</a></div>
    <form className="mb-5 grid gap-3 rounded-xl border bg-[var(--surface)] p-4 sm:grid-cols-2 lg:grid-cols-4">
      <input name="q" aria-label="Search products" placeholder="Search name or SKU" defaultValue={params.q} className="rounded border p-2" />
      <select name="category" aria-label="Category" defaultValue={params.category} className="rounded border p-2"><option value="">All categories</option>{options.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select name="brand" aria-label="Brand" defaultValue={params.brand} className="rounded border p-2"><option value="">All brands</option>{options.brands.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
      <select name="type" aria-label="Product type" defaultValue={params.type} className="rounded border p-2"><option value="">All types</option><option value="simple">Simple</option><option value="variable">Variable</option></select>
      <select name="stock" aria-label="Stock status" defaultValue={params.stock} className="rounded border p-2"><option value="">All stock states</option><option value="in_stock">In stock</option><option value="low_stock">Low stock</option><option value="out_of_stock">Out of stock</option><option value="on_backorder">On backorder</option></select>
      <select name="status" aria-label="Publication status" defaultValue={params.status} className="rounded border p-2"><option value="">All publication states</option><option value="draft">Draft</option><option value="active">Active</option><option value="archived">Archived</option></select>
      <select name="sort" aria-label="Sort products" defaultValue={params.sort} className="rounded border p-2"><option value="updated">Recently updated</option><option value="name">Name</option></select><button className="rounded border px-4 py-2 font-semibold">Apply filters</button>
    </form>
    <form action={archiveProductAction}>{products.length ? <div className="overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[1180px] text-left text-sm"><thead><tr className="border-b"><th className="p-3"><span className="sr-only">Select</span></th><th>Image</th><th>Product</th><th>SKU</th><th>Type</th><th>Category</th><th>Brand</th><th>Price</th><th>Stock</th><th>Warehouses</th><th>Status</th><th>Updated</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} className="border-b align-top"><td className="p-3"><input type="checkbox" name="productIds" value={product.id} aria-label={`Select ${product.name}`} /></td><td>{product.image?.signedUrl ? <img src={product.image.signedUrl} alt={product.image.alt_text ?? product.name} className="h-14 w-20 rounded object-cover" /> : <div className="flex h-12 w-12 items-center justify-center rounded bg-[var(--muted-surface)] text-xs">-</div>}</td><td><a href={`/admin/products/${product.id}`} className="font-semibold">{product.name}</a><span className="block text-xs text-[var(--muted-text)]">{product.variationCount} variations</span></td><td>{product.sku}</td><td>{product.product_type}</td><td>{product.category ?? "-"}</td><td>{product.brand ?? "-"}</td><td>{product.sale_price ?? product.regular_price ?? "-"} {product.currency}</td><td><span className="font-medium">{product.available}</span><span className="block text-xs">{product.derivedStock.replaceAll("_", " ")}</span></td><td className="max-w-52 text-xs">{product.warehouseSummary}</td><td>{product.status}</td><td>{new Date(product.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <p className="rounded-xl border bg-[var(--surface)] p-8 text-center text-[var(--muted-text)]">No products match these filters. Add the first product to begin inventory administration.</p>}<button className="mt-4 rounded border px-4 py-2 font-semibold">Archive selected</button></form>
    <nav className="mt-5 flex justify-between"><a aria-disabled={page <= 1} href={`?page=${Math.max(1, page - 1)}`} className="rounded border px-3 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-50">Previous</a><span>Page {page} of {pages}</span><a aria-disabled={page >= pages} href={`?page=${Math.min(pages, page + 1)}`} className="rounded border px-3 py-2 aria-disabled:pointer-events-none aria-disabled:opacity-50">Next</a></nav>
  </DashboardShell>;
}
