import Image from "next/image";
import { siteConfig } from "@/config/site";
import { capabilities } from "@/components/home/homeData";
import { Button } from "@/components/ui/Button";
import { Section } from "@/components/ui/Section";

export function HeroSection() {
  return <Section className="relative overflow-hidden bg-[#07111f] py-20 text-white sm:py-28"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(125,211,252,.08)_1px,transparent_1px),linear-gradient(rgba(125,211,252,.08)_1px,transparent_1px)] bg-[size:56px_56px]" aria-hidden="true"/><div className="relative grid items-center gap-12 lg:grid-cols-[1.02fr_.98fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-cyan-200">Shenzhen Energy & Networks</p><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-tight sm:text-6xl">Advanced Technology, Sourced Globally and Delivered with Confidence</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">SEN supports corporate procurement for enterprise servers, networking, medical, energy and industrial technology through China sourcing capability, Bangladesh operations and international delivery coordination.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href={siteConfig.publicCtas.exploreProducts.href} size="lg">Explore Products</Button><Button href={siteConfig.publicCtas.requestQuote.href} size="lg" variant="secondary">Request a Quote</Button><Button href="#capabilities" size="lg" variant="outline" className="border-white/25 text-white hover:bg-white/10">Our Capabilities</Button></div><div className="mt-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{capabilities.slice(0,4).map((item)=><span key={item} className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold text-cyan-50">{item}</span>)}</div></div><div className="relative"><div className="absolute -inset-6 rounded-full bg-cyan-400/20 blur-3xl" aria-hidden="true"/><div className="relative overflow-hidden rounded-3xl border border-white/15 bg-white/10 p-3 shadow-2xl"><Image src="/images/home/hero/datacenter.svg" alt="Premium abstract data-center, server and network infrastructure visual" width={1600} height={1000} priority className="aspect-[16/10] w-full rounded-2xl object-cover"/><div className="grid grid-cols-3 border-t border-white/10 text-center text-xs font-semibold uppercase tracking-[0.16em] text-slate-300"><span className="py-4">Compute</span><span className="border-x border-white/10 py-4">Network</span><span className="py-4">Power</span></div></div></div></div></Section>;
}
