export const technologyShowcase = [
  { title: "Enterprise Servers & Data Centers", slug: "servers", href: "/products#servers", image: "/images/home/servers/rack-servers.svg", alt: "Abstract rack server and data-center infrastructure visual", description: "Rack servers, GPU compute classes, storage, racks and power foundations for critical IT environments.", technologies: ["Rack compute", "GPU workloads", "Data-center power", "Virtualization"] },
  { title: "Networking & Fibre Infrastructure", slug: "networking", href: "/products#networking", image: "/images/home/networking/fibre-core.svg", alt: "Abstract enterprise fibre and switching network visual", description: "Core switching, routers, optical modules and fibre infrastructure for enterprise, campus and ISP projects.", technologies: ["Core switching", "Carrier routing", "Optical modules", "ISP access"] },
  { title: "Medical & Laboratory Equipment", slug: "medical", href: "/products#medical", image: "/images/home/medical/diagnostic-suite.svg", alt: "Abstract hospital diagnostic and monitoring equipment visual", description: "Structured sourcing support for diagnostic, patient-monitoring, laboratory and clinical technology categories.", technologies: ["Patient monitoring", "Diagnostics", "Laboratory systems", "Clinical technology"] },
  { title: "Energy, Electrical & Electronics", slug: "energy", href: "/products#energy", image: "/images/home/energy/power-systems.svg", alt: "Abstract energy, UPS and industrial control technology visual", description: "UPS, inverters, PLCs, drives, automation control and power electronics for industrial and energy projects.", technologies: ["UPS systems", "Solar inverters", "PLC controls", "Servo drives"] },
] as const;

export const benefits = ["China sourcing coordination", "Bangladesh operations support", "Technical category understanding", "Requirement-led quotation process", "International shipment coordination", "Supplier and specification checks", "Corporate procurement communication", "Future catalogue-ready data model"] as const;
export const industries = ["Data centers", "Internet service providers", "Healthcare", "Manufacturing", "Energy infrastructure", "Corporate enterprises", "Education", "Government and public infrastructure"] as const;
export const workflow = ["Confirm technical requirement", "Shortlist sourcing options", "Coordinate quotation details", "Verify specifications and documents", "Plan shipment and handover", "Support delivery follow-up"] as const;
export const capabilities = ["Enterprise infrastructure", "Industrial technology", "Medical equipment", "Energy systems", "Global sourcing", "Bangladesh operations"] as const;
export const representativeBrands = ["Dell Technologies", "Cisco", "Huawei", "Siemens", "ABB", "Schneider Electric", "Mitsubishi Electric", "Omron", "Delta", "Supermicro"] as const;
