import { connection } from "next/server";
import { EmployeeHrShell } from "@/components/hr/EmployeeHrShell";
import { getRecruitmentJobApplication } from "@/lib/hr/recruitment-job-application-data";
import { submitRecruitmentJobApplicationAction } from "../actions";

export const dynamic="force-dynamic";
const applicationPath="/employee/hr/recruitment/application";
const Row=({label,value}:{label:string;value:unknown})=><div><dt className="text-xs font-bold uppercase text-[var(--muted-text)]">{label}</dt><dd className="whitespace-pre-wrap">{value===true?"Yes":value===false?"No":String(value??"—")}</dd></div>;
export default async function RecruitmentJobReviewPage({searchParams}:{searchParams:Promise<{error?:string;validation?:string}>}) {
  await connection(); const [state,params]=await Promise.all([getRecruitmentJobApplication(),searchParams]); const a=state.application;
  let validationErrors:Record<string,string>={};
  try { validationErrors=params.validation?JSON.parse(params.validation):{}; } catch { validationErrors={}; }
  const validationEntries=Object.entries(validationErrors);
  if(!a) return <EmployeeHrShell title="Review Job Application" subtitle="No draft exists."><a className="underline" href="/employee/hr/recruitment/application">Start Job Application</a></EmployeeHrShell>;
  const submitted=a.status==="SUBMITTED";
  return <EmployeeHrShell title="Review Job Application" subtitle={submitted?"Submitted applications are locked.":"Review every section before final submission."}>
    {validationEntries.length?<section id="validation" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900"><h2 className="font-bold">Your application cannot be submitted yet.</h2><ul className="mt-2 list-disc space-y-1 pl-5">{validationEntries.map(([field,message])=><li key={field}>{message}</li>)}</ul><a className="mt-3 inline-block rounded-lg border border-red-300 px-3 py-2 font-bold" href={`${applicationPath}?validation=${encodeURIComponent(JSON.stringify(validationErrors))}#employment-application`}>Edit Application</a></section>:params.error?<p id="validation" className="mb-4 rounded-xl bg-red-50 p-3 text-red-800">{params.error}</p>:null}
    <div className="space-y-5">
      <section className="rounded-2xl border p-5"><h2 className="mb-4 text-xl font-bold">Personal Details</h2><dl className="grid gap-4 md:grid-cols-3"><Row label="Full Name" value={a.full_name}/><Row label="Father's Name" value={a.father_name}/><Row label="Mother's Name" value={a.mother_name}/><Row label="Date of Birth" value={a.date_of_birth}/><Row label="Gender" value={a.gender}/><Row label="Marital Status" value={a.marital_status}/><Row label="Nationality" value={a.nationality}/><Row label="Phone" value={a.phone}/><Row label="Email" value={a.email}/><Row label="Present Address" value={a.present_address}/><Row label="Permanent Address" value={a.permanent_address}/><Row label="Emergency Contact" value={`${a.emergency_contact_name??""} ${a.emergency_contact_phone??""} ${a.emergency_contact_relationship??""}`}/></dl></section>
      <section className="rounded-2xl border p-5"><h2 className="mb-4 text-xl font-bold">Identity</h2><dl className="grid gap-4 md:grid-cols-3"><Row label="NID" value={a.nid_number}/><Row label="Passport" value={a.passport_number}/><Row label="Passport Expiry" value={a.passport_expiry_date}/></dl></section>
      <section className="rounded-2xl border p-5"><h2 className="mb-4 text-xl font-bold">Employment / Application</h2><dl className="grid gap-4 md:grid-cols-3"><Row label="Position" value={a.position_applied_for}/><Row label="Joining Date" value={a.preferred_joining_date}/><Row label="Employment Status" value={a.employment_status}/><Row label="Current Employer" value={a.current_employer}/><Row label="Current Designation" value={a.current_designation}/><Row label="Expected Salary" value={a.expected_salary?`${a.expected_salary} ${a.salary_currency}`:"—"}/><Row label="Introduction" value={a.introduction}/></dl></section>
      <section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Education</h2>{state.education.map((r:any)=><dl key={r.id} className="mt-3 grid gap-3 border-t pt-3 md:grid-cols-4"><Row label="Degree" value={r.degree}/><Row label="Institution" value={r.institution}/><Row label="Subject" value={r.subject}/><Row label="Year" value={r.completion_year}/></dl>)}</section>
      <section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Work Experience</h2><Row label="Has Experience" value={a.has_experience}/>{state.experience.map((r:any)=><dl key={r.id} className="mt-3 grid gap-3 border-t pt-3 md:grid-cols-4"><Row label="Company" value={r.company}/><Row label="Designation" value={r.designation}/><Row label="Dates" value={`${r.from_date??""} — ${r.currently_working?"Present":r.to_date??""}`}/><Row label="Responsibilities" value={r.responsibilities}/></dl>)}</section>
      <section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Professional Qualifications</h2><Row label="Has Qualification" value={a.has_qualification}/>{state.qualifications.map((r:any)=><dl key={r.id} className="mt-3 grid gap-3 border-t pt-3 md:grid-cols-3"><Row label="Qualification" value={r.qualification_name}/><Row label="Institution" value={r.institution}/><Row label="Year" value={r.completion_year}/></dl>)}</section>
      <section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Skills</h2>{state.skills.length?state.skills.map((r:any)=><p key={r.id}>{r.skill_name}{r.proficiency?` — ${r.proficiency}`:""}</p>):<p>None added.</p>}</section>
      <section className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Documents</h2>{state.documents.length?<ul className="mt-2 space-y-2">{state.documents.map((d:any)=><li key={d.id}><a className="underline" href={`/employee/hr/recruitment/application/documents/${d.id}`}>{d.title}: {d.original_name}</a></li>)}</ul>:<p>No documents uploaded.</p>}</section>
      {!submitted?<section id="agreement" className="rounded-2xl border p-5"><h2 className="text-xl font-bold">Agreements</h2><form action={submitRecruitmentJobApplicationAction} className="mt-3 space-y-4"><label className="flex gap-3 font-semibold"><input type="checkbox" name="information_confirmed" value="yes"/>I confirm that the information provided is correct.</label><p className="rounded-xl bg-amber-50 p-3">Submit this job application? After final submission, you will not be able to freely edit the core application information.</p><div className="flex gap-3"><a href="/employee/hr/recruitment/application" className="rounded-xl border px-4 py-2 font-bold">Edit Application</a><button className="rounded-xl bg-[var(--primary)] px-4 py-2 font-bold text-[var(--primary-foreground)]">Submit Application</button></div></form></section>:<section className="rounded-2xl bg-emerald-50 p-5"><h2 className="text-xl font-bold text-emerald-800">Application Submitted Successfully</h2><p>{a.application_number} · SUBMITTED · {new Date(a.submitted_at).toLocaleString()}</p></section>}
    </div>
  </EmployeeHrShell>;
}
