export const crmLeadStatuses = ["new", "contacted", "qualified", "proposal", "won", "lost"] as const;
export const crmLeadSources = ["website", "referral", "phone", "email", "social", "event", "existing_customer", "other"] as const;
export const crmLeadPriorities = ["low", "medium", "high", "urgent"] as const;
export const crmActivityTypes = ["note", "call", "email", "meeting", "follow_up"] as const;
export const crmFollowupWorkflowStatuses = ["active", "waiting_customer", "completed", "cancelled", "do_not_contact"] as const;
export const crmFollowupQueueStatuses = ["due", "overdue", "upcoming", "waiting_customer", "completed", "cancelled", "do_not_contact"] as const;
export const crmFollowupReasons = ["price_follow_up", "quotation_follow_up", "purchase_decision", "product_availability", "technical_clarification", "payment_discussion", "sample_follow_up", "general_follow_up", "customer_callback", "other"] as const;
export const crmCommunicationChannels = ["whatsapp", "phone", "email", "messenger", "wechat", "other"] as const;
export const crmActivityDirections = ["inbound", "outbound", "internal"] as const;

export type CrmLeadStatus = (typeof crmLeadStatuses)[number];
export type CrmLeadSource = (typeof crmLeadSources)[number];
export type CrmLeadPriority = (typeof crmLeadPriorities)[number];
export type CrmActivityType = (typeof crmActivityTypes)[number];
export type CrmFollowupWorkflowStatus = (typeof crmFollowupWorkflowStatuses)[number];
export type CrmFollowupQueueStatus = (typeof crmFollowupQueueStatuses)[number];
export type CrmFollowupReason = (typeof crmFollowupReasons)[number];
export type CrmCommunicationChannel = (typeof crmCommunicationChannels)[number];
export type CrmActivityDirection = (typeof crmActivityDirections)[number];
