import { connection } from "next/server";
import { HrPage, hrCard, hrField, hrPrimary, hrSecondary, relation } from "@/components/hr/HrPage";
import { getHrEmployees, getHrLeave } from "@/lib/hr/operational";
import { reviewLeaveAction, saveLeaveBalanceAction, saveLeaveTypeAction } from "../hr-actions";

export const dynamic = "force-dynamic";

export default async function LeavePage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  const [data, employees, params] = await Promise.all([getHrLeave(),getHrEmployees({pageSize:100,status:"all"}),searchParams]);
  return <HrPage title="Leave management" subtitle="Leave requests, approval, types and annual balances." success={params.success} error={params.error}>
    <section className="grid gap-4 xl:grid-cols-2"><form action={saveLeaveTypeAction} className={hrCard}><input type="hidden" name="return_to" value="/admin/hr/leaves"/><h2 className="font-semibold">Create leave type</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Code<input name="code" required className={hrField}/></label><label className="text-sm font-semibold">Name<input name="name" required className={hrField}/></label><label className="text-sm font-semibold">Default days<input name="default_days" type="number" min="0" step=".5" className={hrField}/></label></div><div className="mt-3 flex gap-4 text-sm"><label><input type="checkbox" name="is_paid" defaultChecked/> Paid</label><label><input type="checkbox" name="requires_document"/> Document required</label><label><input type="checkbox" name="is_active" defaultChecked/> Active</label></div><button className={`${hrPrimary} mt-3`}>Create type</button></form>
      <form action={saveLeaveBalanceAction} className={hrCard}><input type="hidden" name="return_to" value="/admin/hr/leaves"/><h2 className="font-semibold">Allocate leave balance</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Employee<select name="employee_record_id" required className={hrField}><option value="">Select employee</option>{employees.rows.map(e=><option key={e.id} value={e.id}>{relation(e.profiles)?.full_name||e.employee_number}</option>)}</select></label><label className="text-sm font-semibold">Leave type<select name="leave_type_id" required className={hrField}>{data.types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="text-sm font-semibold">Year<input name="leave_year" type="number" defaultValue={new Date().getFullYear()} className={hrField}/></label><label className="text-sm font-semibold">Allocated days<input name="allocated_days" type="number" min="0" step=".5" className={hrField}/></label></div><input type="hidden" name="adjusted_days" value="0"/><button className={`${hrPrimary} mt-3`}>Save balance</button></form></section>
    <section className="mt-5 space-y-3">{data.requests.map(item=>{const employee=relation(item.hr_employee_records);const person=employee?relation(employee.profiles):null;return <article key={item.id} className={hrCard}><div className="flex flex-wrap justify-between gap-3"><div><strong>{person?.full_name||employee?.employee_number}</strong><p className="text-sm text-[var(--muted-text)]">{relation(item.hr_leave_types)?.name||item.leave_type} · {item.start_date} to {item.end_date}</p></div><span className="capitalize">{item.status}</span></div><p className="mt-2 text-sm">{item.reason||"No reason supplied."}</p>{item.status==="pending"?<form action={reviewLeaveAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="leave_id" value={item.id}/><input type="hidden" name="return_to" value="/admin/hr/leaves"/><input name="review_note" placeholder="Review note" className={`${hrField} min-w-60 flex-1`}/><button name="decision" value="approved" className={hrPrimary}>Approve</button><button name="decision" value="rejected" className={hrSecondary}>Reject</button></form>:null}</article>})}{!data.requests.length?<p className={hrCard}>No leave requests yet.</p>:null}</section>
  </HrPage>;
}
