/* eslint-disable @next/next/no-img-element */
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSerialLabelAssets } from "@/lib/inventory/labels";
import { regenerateSerialAction,updateManufacturerSerialAction } from "../actions";

export const dynamic="force-dynamic";
export default async function SerialDetail({ params,searchParams }: { params: Promise<{ id: string }>;searchParams:Promise<{success?:string;error?:string}> }) {
  const { profile, permissions } = await requirePermission("serials.view"); const [{ id },message] = await Promise.all([params,searchParams]); const db = createSupabaseAdminClient();
  const { data: serial,error } = await db.from("serial_numbers").select("*").eq("id", id).maybeSingle(); if(error)throw new Error("Unable to load serial.");if (!serial) notFound();
  const [{ data: product }, { data: variation }, { data: warehouse }, { data: movement },{data:history},{data:events}] = await Promise.all([
    db.from("products").select("id,name,sku,model_number,brand_id,brands(name)").eq("id", serial.product_id).maybeSingle(),
    serial.variation_id ? db.from("product_variations").select("id,sku,combination_key").eq("id", serial.variation_id).maybeSingle() : Promise.resolve({ data: null }),
    serial.warehouse_id?db.from("warehouses").select("id,name,code,country_name").eq("id", serial.warehouse_id).maybeSingle():Promise.resolve({data:null}),
    serial.last_movement_id ? db.from("inventory_movements").select("id,reference,movement_type,created_at").eq("id", serial.last_movement_id).maybeSingle() : Promise.resolve({ data: null }),
    db.from("serial_number_history").select("id,event_type,previous_sen_serial,new_sen_serial,previous_status,new_status,reason,occurred_at,movement_id").eq("serial_number_id",id).order("occurred_at",{ascending:false}).limit(100),
    db.from("serial_tracking_events").select("id,event_type,workplace_name_snapshot,city_snapshot,country_snapshot,location_source,note,occurred_at,tracking_status_definitions(name)").eq("serial_number_id",id).order("occurred_at",{ascending:false}).limit(100),
  ]);
  const rows = [["Manufacturer serial", serial.manufacturer_serial??"Not provided"],["SEN serial",serial.sen_serial],["Barcode",serial.barcode_value],["Product",product?`${product.name} (${product.sku})`:serial.product_id],["Model",product?.model_number],["Variation",variation?`${variation.combination_key} (${variation.sku})`:"Parent product"],["Warehouse",warehouse?`${warehouse.name} (${warehouse.code})`:"Expected location not set"],["Status",serial.status],["Condition",serial.condition],["Acquisition reference",serial.acquisition_reference],["Warranty start",serial.warranty_start],["Warranty end",serial.warranty_end],["Notes",serial.notes]];
  const assets=serial.sen_serial?await createSerialLabelAssets(serial.sen_serial):null;
  return <DashboardShell admin={profile.role === "admin"} employeePermissions={profile.role === "employee" ? permissions : undefined} title={serial.sen_serial??serial.manufacturer_serial??"Serialized unit"} subtitle="Physical-unit identity, label and append-only history.">
    {message.success?<p className="mb-4 rounded border border-green-200 bg-green-50 p-3 text-green-900">{message.success}</p>:null}{message.error?<p className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-red-900">{message.error}</p>:null}
    <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><section className="rounded-xl border bg-[var(--surface)] p-6"><dl className="grid gap-4 md:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-sm text-[var(--muted-text)]">{label}</dt><dd className="break-words font-medium">{value??"—"}</dd></div>)}</dl></section>{assets?<aside className="rounded-xl border bg-white p-5 text-black"><h2 className="font-semibold">Label preview</h2><div className="mt-3" dangerouslySetInnerHTML={{__html:assets.barcodeSvg}}/><p className="break-all text-center font-mono text-xs">{serial.sen_serial}</p><img src={assets.qrDataUrl} alt="Serial QR code" className="mx-auto mt-3 h-36 w-36"/><a href={`/admin/serials/print?ids=${id}`} className="mt-4 block rounded border px-4 py-2 text-center font-semibold">Print label</a></aside>:null}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><form action={updateManufacturerSerialAction} className="rounded-xl border bg-[var(--surface)] p-5"><input type="hidden" name="serial_id" value={id}/><h2 className="font-semibold">Manufacturer serial</h2><input name="manufacturer_serial" defaultValue={serial.manufacturer_serial??""} placeholder="Optional" className="mt-3 w-full rounded border p-3"/><button className="mt-3 rounded border px-4 py-2 font-semibold">Save manufacturer serial</button></form>{serial.status==="expected"?<form action={regenerateSerialAction} className="rounded-xl border border-amber-300 bg-amber-50 p-5"><input type="hidden" name="serial_id" value={id}/><h2 className="font-semibold text-amber-950">Regenerate expected serial</h2><input name="reason" required placeholder="Required reason" className="mt-3 w-full rounded border p-3"/><button className="mt-3 rounded border border-amber-700 px-4 py-2 font-semibold text-amber-950">Regenerate with history</button></form>:null}</div>
    <section className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Unit history</h2>{history?.length?<ol className="mt-4 space-y-3">{history.map((item)=><li key={item.id} className="rounded border p-3"><strong>{item.event_type.replaceAll("_"," ")}</strong><span className="block text-sm text-[var(--muted-text)]">{new Date(item.occurred_at).toLocaleString()} · {item.previous_status??"—"} → {item.new_status??"—"}</span>{item.previous_sen_serial&&item.previous_sen_serial!==item.new_sen_serial?<span className="block break-all font-mono text-xs">{item.previous_sen_serial} → {item.new_sen_serial}</span>:null}{item.reason?<p className="mt-1 text-sm">{item.reason}</p>:null}</li>)}</ol>:<p className="mt-3 text-[var(--muted-text)]">No history events recorded.</p>}</section>
    <section className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Location and tracking events</h2>{events?.length?<ol className="mt-4 space-y-3">{events.map((item)=>{const status=item.tracking_status_definitions as unknown as {name:string}|null;return <li key={item.id} className="rounded border p-3"><strong>{status?.name??item.event_type.replaceAll("_"," ")}</strong><span className="block text-sm text-[var(--muted-text)]">{new Date(item.occurred_at).toLocaleString()} · {item.workplace_name_snapshot??"Location unavailable"} · {item.location_source.replaceAll("_"," ")}</span>{item.note?<p className="mt-1 text-sm">{item.note}</p>:null}</li>})}</ol>:<p className="mt-3 text-[var(--muted-text)]">No location events recorded.</p>}</section>
    <section className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Last inventory movement</h2>{movement?<p className="mt-3"><a href={`/admin/inventory/movements/${movement.id}`} className="font-semibold">{movement.reference}</a><span className="block text-sm text-[var(--muted-text)]">{movement.movement_type.replaceAll("_"," ")} · {new Date(movement.created_at).toLocaleString()}</span></p>:<p className="mt-3 text-[var(--muted-text)]">No movement reference is recorded.</p>}</section>
  </DashboardShell>;
}
