import { connection } from "next/server";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requireAnyPermission } from "@/lib/auth/permissions";
import { getSale } from "@/lib/sales/data";
import { dateTime,label,money } from "@/lib/orders/types";
import { cancelSaleAction,confirmSaleAction,generateSaleDocumentAction,recordPaymentAction } from "../actions";
export const dynamic="force-dynamic";
const field="rounded-lg border bg-[var(--surface)] px-3 py-2";
export default async function SaleDetail({params,searchParams}:{params:Promise<{saleId:string}>;searchParams:Promise<{success?:string;error?:string}>}) {
  await connection(); const {profile,permissions}=await requireAnyPermission(["sales.view","sales.view_all","sales.view_own"]),{saleId}=await params,notice=await searchParams,data=await getSale(saleId); if(!data)notFound();
  if(profile.role==="employee"&&!permissions.has("sales.view")&&!permissions.has("sales.view_all")&&data.order.created_by!==profile.id)notFound();
  const {order,items,reservations,allocations,payments,adjustments,documents,shipments,events,audit}=data,customer=order.customer as {full_name:string|null;email:string;phone:string|null;company_name:string|null},employee=order.employee as {full_name:string|null;email:string};
  const outstanding=Math.max(Number(order.total_amount)-Number(order.paid_amount),0),activeReservations=reservations.filter(x=>x.status==="active"),activeAllocations=allocations.filter(x=>!["released","cancelled"].includes(x.status));
  return <DashboardShell admin={profile.role==="admin"} employeePermissions={profile.role==="employee"?permissions:undefined} title={order.order_number} subtitle="Sale detail, pricing, reservation, serials, payments, documents and shipment handoff.">
    {notice.success?<p className="mb-3 rounded-lg border border-green-200 bg-green-50 p-3 text-green-900">{notice.success}</p>:null}{notice.error?<p className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3 text-red-900">{notice.error}</p>:null}
    <section className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{[["Sale status",label(order.status)],["Payment",label(order.payment_status)],["Total",money(order.total_amount,order.currency)],["Paid",money(order.paid_amount,order.currency)],["Outstanding",money(outstanding,order.currency)],["Reserved",activeReservations.length],["Serials",activeAllocations.length],["Shipments",shipments.length]].map(([name,value])=><article key={name} className="rounded-xl border bg-[var(--surface)] p-3"><p className="text-xs text-[var(--muted-text)]">{name}</p><strong className="mt-1 block text-lg">{value}</strong></article>)}</section>
    <div className="mt-3 flex flex-wrap gap-2">{order.status==="draft"?<form action={confirmSaleAction.bind(null,saleId)}><button className="rounded-lg bg-[var(--primary)] px-4 py-2 font-bold text-[var(--primary-foreground)]">Confirm sale & reserve stock</button></form>:null}{!["draft","cancelled","delivered"].includes(order.status)?<a href={`/admin/orders/${saleId}/allocate`} className="rounded-lg border px-4 py-2 font-semibold">Allocate / scan serials</a>:null}{!["draft","cancelled","delivered"].includes(order.status)?<a href={`/admin/orders/${saleId}/pack`} className="rounded-lg border px-4 py-2 font-semibold">Pack sale</a>:null}{!["draft","cancelled","delivered"].includes(order.status)?<a href={`/admin/orders/${saleId}/shipments/new`} className="rounded-lg border px-4 py-2 font-semibold">Create shipment / partial shipment</a>:null}<a href={`/admin/orders/${saleId}`} className="rounded-lg border px-4 py-2 font-semibold">Open fulfilment view</a>{!["cancelled","delivered","shipped"].includes(order.status)?<form action={cancelSaleAction.bind(null,saleId)} className="flex gap-2"><input name="reason" required placeholder="Cancellation reason" className={field}/><button className="rounded-lg border border-red-300 px-4 py-2 font-semibold text-red-800">Cancel sale</button></form>:null}</div>
    <section className="mt-4 grid gap-3 xl:grid-cols-[1.4fr_.6fr]"><div className="space-y-3">
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Products & pricing</h2><div className="mt-3 space-y-2">{items.map(item=>{const itemSerials=activeAllocations.filter(a=>a.order_item_id===item.id);return <div key={item.id} className="rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.product_name_snapshot}</b><p className="text-xs text-[var(--muted-text)]">{item.brand_snapshot} · {item.model_number_snapshot} · SKU {item.sku_snapshot}</p></div><div className="text-right"><b>{item.quantity} × {money(item.unit_price,item.currency)}</b><p>{money(item.line_total,item.currency)}</p></div></div><div className="mt-2 flex flex-wrap gap-2 text-xs"><span>Reserved {activeReservations.filter(r=>r.order_item_id===item.id).reduce((n,r)=>n+Number(r.quantity),0)}</span><span>Allocated {item.allocated_quantity}</span><span>Packed {item.packed_quantity}</span><span>Shipped {item.shipped_quantity}</span>{item.serial_tracking_required_snapshot?<span className={itemSerials.length===Number(item.quantity)?"text-green-700":"font-bold text-amber-700"}>Serials {itemSerials.length}/{item.quantity}</span>:null}</div>{itemSerials.length?<ul className="mt-2 grid gap-1 md:grid-cols-2">{itemSerials.map(a=>{const s=a.serial_numbers as {sen_serial:string;manufacturer_serial:string|null};return <li key={a.id} className="rounded bg-[var(--muted-surface)] p-2 text-xs"><b>{s.sen_serial}</b>{s.manufacturer_serial?` · ${s.manufacturer_serial}`:""} · {label(a.status)}</li>})}</ul>:null}</div>})}</div><div className="mt-3 border-t pt-3 text-right"><p>Subtotal {money(order.subtotal,order.currency)}</p><p>Order discount {money(order.discount_amount,order.currency)}</p><p>Shipping {money(order.shipping_amount,order.currency)}</p><p>Service {money(order.service_amount,order.currency)}</p><p>VAT/tax {money(order.tax_amount,order.currency)}</p><b className="text-xl">Final total {money(order.total_amount,order.currency)}</b></div></article>
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Payments</h2><form action={recordPaymentAction.bind(null,saleId)} className="mt-3 grid gap-2 md:grid-cols-3 xl:grid-cols-6"><input name="amount" type="number" min=".01" step=".01" max={outstanding||undefined} placeholder="Amount" required className={field}/><input name="payment_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className={field}/><select name="method" className={field}>{["cash","bank_transfer","cheque","mobile_banking","card","credit_sale","advance_payment","cash_on_delivery","other"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><input name="reference_number" placeholder="Reference" className={field}/><input name="internal_note" placeholder="Internal note" className={field}/><button className="rounded-lg bg-slate-900 px-3 py-2 font-semibold text-white">Record payment</button></form><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Received by</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.id} className="border-t"><td className="py-2">{payment.payment_date}</td><td>{money(payment.amount,order.currency)}</td><td>{label(payment.method)}</td><td>{payment.reference_number||"—"}</td><td>{(payment.profiles as {full_name:string|null;email:string})?.full_name||(payment.profiles as {email:string})?.email}</td></tr>)}</tbody></table>{!payments.length?<p className="py-4 text-sm text-[var(--muted-text)]">No payments recorded.</p>:null}</div></article>
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Documents</h2><div className="mt-3 flex flex-wrap gap-2"><form action={generateSaleDocumentAction.bind(null,saleId,"invoice")}><button className="rounded-lg bg-[var(--primary)] px-4 py-2 font-semibold text-[var(--primary-foreground)]">Generate Invoice</button></form><form action={generateSaleDocumentAction.bind(null,saleId,"delivery_challan")}><button className="rounded-lg border px-4 py-2 font-semibold">Generate Delivery Challan</button></form>{documents.map(document=><a key={document.id} href={`/admin/sales/${saleId}/documents/${document.id}`} className="rounded-lg border px-4 py-2 font-semibold">{document.document_number} · Print / PDF</a>)}</div></article>
    </div><aside className="space-y-3">
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Customer</h2><p className="mt-2"><b>{customer.full_name||customer.email}</b><br/>{customer.company_name}<br/>{customer.email}<br/>{customer.phone}</p><a href={`/admin/users/${order.customer_profile_id}`} className="mt-3 inline-block font-semibold text-[var(--primary)]">View customer profile & history →</a></article>
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Sale information</h2><dl className="mt-2 space-y-2 text-sm"><div><dt className="text-[var(--muted-text)]">Employee</dt><dd>{employee.full_name||employee.email}</dd></div><div><dt className="text-[var(--muted-text)]">Source</dt><dd>{label(order.sales_source)}</dd></div><div><dt className="text-[var(--muted-text)]">Expected delivery</dt><dd>{order.expected_delivery_date||"—"}</dd></div><div><dt className="text-[var(--muted-text)]">Created</dt><dd>{dateTime(order.created_at)}</dd></div></dl></article>
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Shipments</h2>{shipments.map(shipment=><a key={shipment.id} href={`/admin/shipments/${shipment.id}`} className="mt-2 block rounded-lg border p-3"><b>{shipment.shipment_number}</b><br/><span className="text-sm">{label(shipment.status)} · View tracking →</span></a>)}{!shipments.length?<p className="mt-2 text-sm text-[var(--muted-text)]">No shipment created.</p>:null}</article>
      <article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Activity & price changes</h2><p className="text-sm text-[var(--muted-text)]">{events.length+audit.length} operational activity records · {adjustments.length} price adjustment(s).</p>{adjustments.slice(0,5).map(a=><p key={a.id} className="mt-2 rounded bg-[var(--muted-surface)] p-2 text-xs">{label(a.adjustment_type)}: {money(a.previous_value,order.currency)} → {money(a.new_value,order.currency)}<br/>{a.reason}</p>)}</article>
    </aside></section>
  </DashboardShell>;
}
