"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireProfile } from "@/lib/auth/session";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { wholeNumberFromForm } from "@/lib/validation/numbers";
export async function requestQuotationAction(form:FormData){const{profile}=await requireProfile(["customer","admin"]),db=createSupabaseAdminClient(),productId=String(form.get("product_id")??"");let quantity:number;try{quantity=wholeNumberFromForm(form,"quantity","Quantity",{required:true,minimum:1})!;}catch(error){redirect(`/products/${String(form.get("slug"))}?error=${encodeURIComponent(error instanceof Error?error.message:"Quantity is invalid.")}`);}const{data:product}=await db.from("products").select("id,name,sku").eq("id",productId).eq("status","active").maybeSingle();if(!product)redirect("/products?error=Product%20not%20found.");const reference=`RFQ-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const{data:quote,error}=await db.from("quotation_requests").insert({reference,profile_id:profile.id,subject:String(form.get("subject")||`Quotation for ${product.name}`).slice(0,200),message:String(form.get("message")??"").slice(0,5000),company_name:profile.company_name}).select("id").single();if(error||!quote)redirect(`/products/${String(form.get("slug"))}?error=Unable%20to%20request%20quotation.`);await db.from("quotation_request_items").insert({quotation_id:quote.id,product_id:product.id,product_name_snapshot:product.name,sku_snapshot:product.sku,quantity});revalidatePath("/account/quotations");redirect(`/account/quotations?success=${encodeURIComponent(`Quotation ${reference} submitted.`)}`);}

export async function requestGeneralQuotationAction(form: FormData) { const { profile } = await requireProfile(["customer", "admin"]); const db = createSupabaseAdminClient(); let quantity:number;try{quantity=wholeNumberFromForm(form,"quantity","Quantity",{required:true,minimum:1})!;}catch(error){redirect(`/request-quote/general?error=${encodeURIComponent(error instanceof Error?error.message:"Quantity is invalid.")}`);} const reference = `RFQ-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,8).toUpperCase()}`; const { data: quote, error } = await db.from("quotation_requests").insert({ reference, profile_id: profile.id, subject: String(form.get("subject") || "General quotation request").slice(0,200), message: String(form.get("message") ?? "").slice(0,5000), company_name: profile.company_name }).select("id").single(); if (error || !quote) redirect(`/request-quote/general?error=${encodeURIComponent("Unable to submit quotation request.")}`); const item = await db.from("quotation_request_items").insert({ quotation_id: quote.id, product_name_snapshot: "General requirement", sku_snapshot: null, quantity }); if (item.error) { await db.from("quotation_requests").delete().eq("id", quote.id); redirect(`/request-quote/general?error=${encodeURIComponent("Unable to save quotation details.")}`); } revalidatePath("/account/quotations"); redirect(`/account/quotations?success=${encodeURIComponent(`Quotation ${reference} submitted.`)}`); }
