import Link from "next/link";
import { updateUserByAdminAction } from "@/lib/auth/actions";
import { requireAdmin } from "@/lib/auth/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import type { AccountRole, AccountStatus, Profile } from "@/lib/auth/types";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string; role?: AccountRole; status?: AccountStatus }> }) {
  const profile = await requireAdmin();
  const sp = await searchParams;
  const client = createSupabaseAdminClient();
  let query = client.from("profiles").select("*").order("created_at", { ascending: false }).limit(50);
  if (sp.role) query = query.eq("role", sp.role);
  if (sp.status) query = query.eq("status", sp.status);
  if (sp.q) query = query.or(`full_name.ilike.%${sp.q}%,email.ilike.%${sp.q}%`);
  const { data, error } = await query.returns<Profile[]>();
  return <main className="min-h-screen bg-[var(--muted-surface)] p-6"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-center justify-between"><div><Link href="/admin" className="text-sm font-semibold">← Admin</Link><h1 className="text-3xl font-bold">Users</h1><p className="text-sm text-[var(--muted-text)]">Signed in as {profile.email}</p></div></div><form className="mb-5 grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 md:grid-cols-4"><input name="q" placeholder="Search name or email" defaultValue={sp.q ?? ""} className="rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/><select name="role" defaultValue={sp.role ?? ""} className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2"><option value="">All roles</option><option value="customer">Customer</option><option value="employee">Employee</option><option value="admin">Admin</option></select><select name="status" defaultValue={sp.status ?? ""} className="rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2"><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option></select><button className="rounded-lg bg-[var(--primary)] px-4 py-2 text-[var(--primary-foreground)]">Filter</button></form>{error ? <p>Unable to load users.</p> : <div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-3">User</th><th>Role</th><th>Status</th><th>Country</th><th>Manage</th></tr></thead><tbody>{(data ?? []).map(user => <tr key={user.id} className="border-b border-[var(--border)]"><td className="p-3"><Link className="font-semibold" href={`/admin/users/${user.id}`}>{user.full_name}</Link><p className="text-[var(--muted-text)]">{user.email}</p></td><td>{user.role}</td><td>{user.status}</td><td>{user.country_name}</td><td><form action={updateUserByAdminAction} className="flex gap-2"><input type="hidden" name="userId" value={user.id}/><select name="role" defaultValue={user.role} className="rounded border border-[var(--border)] bg-[var(--surface)] p-1"><option value="customer">customer</option><option value="employee">employee</option><option value="admin">admin</option></select><select name="status" defaultValue={user.status} className="rounded border border-[var(--border)] bg-[var(--surface)] p-1"><option value="active">active</option><option value="suspended">suspended</option><option value="disabled">disabled</option></select><button className="rounded bg-[var(--primary)] px-3 py-1 text-[var(--primary-foreground)]">Update</button></form></td></tr>)}</tbody></table></div>}</div></main>;
}
