import { connection } from "next/server";
import { DashboardShell } from "@/components/dashboard/Shell";
import { PermissionChecklist } from "@/components/permissions/PermissionChecklist";
import { requireProfile } from "@/lib/auth/session";
import { getPermissionCatalogue, getPermissionTemplates } from "@/lib/auth/permissions";
import { duplicateTemplateAction, saveTemplateAction, toggleTemplateAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminPermissionsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  await requireProfile(["admin"]);
  const [modules, templates, message] = await Promise.all([getPermissionCatalogue(), getPermissionTemplates(true), searchParams]);
  return <DashboardShell admin title="Permissions" subtitle="Manage permission modules and reusable employee templates.">
    {message.success ? <p className="mb-5 rounded border border-green-200 bg-green-50 p-3 text-green-900">{message.success}</p> : null}
    {message.error ? <p className="mb-5 rounded border border-red-200 bg-red-50 p-3 text-red-900">{message.error}</p> : null}
    <section className="grid gap-4 md:grid-cols-3">{templates.map((template) => <article key={template.id} className="rounded-xl border bg-[var(--surface)] p-5"><div className="flex items-start justify-between gap-2"><h2 className="font-semibold">{template.name}</h2>{template.is_default ? <span className="rounded bg-green-100 px-2 py-1 text-xs text-green-900">Default</span> : null}</div><p className="mt-2 text-sm text-[var(--muted-text)]">{template.permissionKeys.length} permissions · {template.is_active ? "Active" : "Inactive"}</p><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">View permissions</summary><ul className="mt-2 space-y-1 text-xs text-[var(--muted-text)]">{template.permissionKeys.map((key) => <li key={key}>{key}</li>)}</ul></details><div className="mt-4 flex flex-wrap gap-2"><form action={duplicateTemplateAction}><input type="hidden" name="templateId" value={template.id}/><button className="rounded border px-3 py-2 text-sm font-semibold">Duplicate</button></form>{!template.is_system ? <form action={toggleTemplateAction}><input type="hidden" name="templateId" value={template.id}/><button className="rounded border px-3 py-2 text-sm font-semibold">{template.is_active ? "Deactivate" : "Activate"}</button></form> : <span className="text-xs text-[var(--muted-text)]">Protected system template</span>}</div></article>)}</section>
    {templates.filter((template) => !template.is_system).map((template) => <details key={`edit-${template.id}`} className="mt-6 rounded-xl border bg-[var(--surface)] p-6"><summary className="cursor-pointer text-lg font-semibold">Edit {template.name}</summary><form action={saveTemplateAction} className="mt-5 space-y-5"><input type="hidden" name="templateId" value={template.id}/><div className="grid gap-4 md:grid-cols-2"><label>Name<input name="name" required defaultValue={template.name} className="mt-1 w-full rounded border p-3"/></label><label>Description<input name="description" defaultValue={template.description ?? ""} className="mt-1 w-full rounded border p-3"/></label></div><PermissionChecklist modules={modules} initialSelected={template.permissionKeys}/><button className="rounded bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)]">Save template</button></form></details>)}
    <section className="mt-8 rounded-xl border bg-[var(--surface)] p-6"><h2 className="text-xl font-semibold">Create custom template</h2><form action={saveTemplateAction} className="mt-5 space-y-5"><div className="grid gap-4 md:grid-cols-2"><label>Name<input name="name" required className="mt-1 w-full rounded border p-3"/></label><label>Description<input name="description" className="mt-1 w-full rounded border p-3"/></label></div><PermissionChecklist modules={modules} initialSelected={[]} /><button className="rounded bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)]">Create template</button></form></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Module catalogue</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{modules.map((module) => <article key={module.id} className="rounded-xl border bg-[var(--surface)] p-4"><h3 className="font-semibold">{module.name}</h3><p className="text-sm text-[var(--muted-text)]">{module.permissions.length} permissions · {module.is_implemented ? "Implemented foundation" : "Planned module"}</p></article>)}</div></section>
  </DashboardShell>;
}
