import { connection } from "next/server";
import { HrPage, hrCard, hrField, hrPrimary, relation } from "@/components/hr/HrPage";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getHrEmployees, getHrReferences } from "@/lib/hr/operational";
import { createAttendanceDeviceAction, saveDeviceMappingAction, saveHrSettingsAction } from "../hr-actions";

export const dynamic = "force-dynamic";

export default async function HrSettingsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  const db = createSupabaseAdminClient();
  const [settingsResult,mappingResult,refs,employees,notices] = await Promise.all([
    db.from("hr_settings").select("*").eq("id",true).maybeSingle(),
    db.from("hr_device_employee_mappings").select("*,hr_attendance_devices(name,code),hr_employee_records(employee_number,profiles:profiles!hr_employee_records_profile_id_fkey(full_name))").order("created_at",{ascending:false}).limit(100),
    getHrReferences(), getHrEmployees({pageSize:100,status:"all"}), searchParams,
  ]);
  if (settingsResult.error || mappingResult.error) throw new Error("Unable to load HR settings.");
  const settings = settingsResult.data;
  return <HrPage title="HR settings & attendance devices" subtitle="Configure work rules now and connect fingerprint/camera gateways later without storing biometric templates." success={notices.success} error={notices.error}>
    <section className="grid gap-4 xl:grid-cols-2">
      <form action={saveHrSettingsAction} className={hrCard}><input type="hidden" name="return_to" value="/admin/hr/settings"/><h2 className="font-semibold">Work rules</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Workday starts<input type="time" name="workday_start" defaultValue={settings?.workday_start?.slice(0,5) ?? "09:00"} required className={hrField}/></label><label className="text-sm font-semibold">Workday ends<input type="time" name="workday_end" defaultValue={settings?.workday_end?.slice(0,5) ?? "18:00"} required className={hrField}/></label><label className="text-sm font-semibold">Late grace (minutes)<input type="number" min="0" max="240" name="late_grace_minutes" defaultValue={settings?.late_grace_minutes ?? 15} required className={hrField}/></label><label className="text-sm font-semibold">Leave year starts (month)<input type="number" min="1" max="12" name="leave_year_start_month" defaultValue={settings?.leave_year_start_month ?? 1} required className={hrField}/></label></div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="device_ingestion_enabled" defaultChecked={settings?.device_ingestion_enabled ?? false}/> Enable device event ingestion</label><button className={`${hrPrimary} mt-3`}>Save settings</button></form>
      <form action={createAttendanceDeviceAction} className={hrCard}><input type="hidden" name="return_to" value="/admin/hr/settings"/><h2 className="font-semibold">Register attendance device/gateway</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Code<input name="code" required pattern="[A-Za-z0-9-]{2,40}" className={hrField}/></label><label className="text-sm font-semibold">Name<input name="name" required className={hrField}/></label><label className="text-sm font-semibold">Type<select name="device_type" className={hrField}>{["fingerprint","camera","hybrid","gateway","other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Work location<select name="work_location_id" className={hrField}><option value="">Not assigned</option>{refs.locations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-semibold">Vendor<input name="vendor" className={hrField}/></label><label className="text-sm font-semibold">Model<input name="model" className={hrField}/></label><label className="text-sm font-semibold sm:col-span-2">Serial number<input name="serial_number" className={hrField}/></label></div><button className={`${hrPrimary} mt-3`}>Register and generate API key</button></form>
    </section>
    <form action={saveDeviceMappingAction} className={`${hrCard} mt-4`}><input type="hidden" name="return_to" value="/admin/hr/settings"/><h2 className="font-semibold">Map device employee ID</h2><div className="mt-3 grid gap-3 md:grid-cols-4"><label className="text-sm font-semibold">Device<select name="device_id" required className={hrField}><option value="">Select device</option>{refs.devices.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select></label><label className="text-sm font-semibold">SEN employee<select name="employee_record_id" required className={hrField}><option value="">Select employee</option>{employees.rows.map(x=><option key={x.id} value={x.id}>{relation(x.profiles)?.full_name ?? x.employee_number}</option>)}</select></label><label className="text-sm font-semibold">Device employee ID<input name="external_employee_id" required className={hrField}/></label><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" name="is_active" defaultChecked/> Active mapping</label></div><button className={hrPrimary}>Save mapping</button></form>
    <section className={`${hrCard} mt-4`}><h2 className="font-semibold">Registered devices and mappings</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Device</th><th>Employee</th><th>External ID</th><th>Status</th></tr></thead><tbody>{(mappingResult.data ?? []).map(row=>{const device=relation(row.hr_attendance_devices);const employee=relation(row.hr_employee_records);return <tr key={row.id} className="border-t"><td className="py-2">{device?.name} ({device?.code})</td><td>{relation(employee?.profiles)?.full_name ?? employee?.employee_number}</td><td>{row.external_employee_id}</td><td>{row.is_active ? "Active":"Inactive"}</td></tr>})}</tbody></table>{!mappingResult.data?.length?<p className="py-3 text-sm text-[var(--muted-text)]">No device mappings yet.</p>:null}</div></section>
  </HrPage>;
}
