import Link from "next/link";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requireProfile } from "@/lib/auth/session";
import { getDonationBeneficiaryDetail, getDonationOptions, type TrendPeriod } from "@/lib/donation-expenses/data";
import { saveDonationMonthlySupportAction } from "../../actions";

export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT" }).format(value);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) : "—";

export default async function DonationBeneficiaryPage({ params, searchParams }: { params: Promise<{ beneficiaryId: string }>; searchParams: Promise<{ period?: TrendPeriod; from?: string; to?: string; success?: string; error?: string }> }) {
  await connection(); await requireProfile(["admin"]);
  const [{ beneficiaryId }, query] = await Promise.all([params, searchParams]);
  const period: TrendPeriod = ["3m", "12m", "1y", "3y", "custom"].includes(query.period ?? "") ? query.period! : "12m";
  const [detail, options] = await Promise.all([getDonationBeneficiaryDetail(beneficiaryId, period, query.from, query.to), getDonationOptions()]);
  if (!detail) notFound();
  const { beneficiary, expenses, summary, trend } = detail;
  const max = Math.max(...trend.map((item) => item.amount), 1);
  const input = "rounded-lg border bg-background px-3 py-2";
  return <DashboardShell admin title={beneficiary.name} subtitle={`${beneficiary.beneficiary_reference} · ${beneficiary.beneficiary_type.replaceAll("_", " ")}`}>
    {query.success ? <p className="mb-4 rounded-lg border border-green-200 bg-green-50 p-3 text-green-900">{query.success}</p> : null}
    {query.error ? <p className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-red-900">{query.error}</p> : null}
    <div className="mb-5 flex gap-2"><Link href="/admin/donation-expenses/beneficiaries" className="rounded-lg border px-4 py-2 font-semibold">Beneficiaries</Link><Link href={`/admin/donation-expenses?beneficiary=${beneficiary.id}#create-donation`} className="rounded-lg bg-[var(--primary)] px-4 py-2 font-semibold text-[var(--primary-foreground)]">Create Donation</Link></div>
    <section className="mb-5 grid gap-4 lg:grid-cols-3">
      <div className="rounded-xl border bg-[var(--surface)] p-5"><h2 className="font-semibold">Contact</h2><p className="mt-2 text-sm">{beneficiary.phone || "No phone"}<br />{beneficiary.alternate_phone || ""}<br />{beneficiary.whatsapp ? `WhatsApp: ${beneficiary.whatsapp}` : ""}<br />{[beneficiary.address, beneficiary.city_district, beneficiary.country].filter(Boolean).join(", ") || "No address"}</p></div>
      <div className="rounded-xl border bg-[var(--surface)] p-5"><h2 className="font-semibold">Relationship</h2><p className="mt-2 text-sm">{beneficiary.relationship_group || "Not specified"}<br />{beneficiary.relationship_type?.name || ""}<br />{beneficiary.relationship_note || ""}</p></div>
      <div className="rounded-xl border bg-[var(--surface)] p-5"><h2 className="font-semibold">Referred / Introduced By</h2><p className="mt-2 text-sm">{beneficiary.referred_by_name || "Not specified"}<br />{beneficiary.referred_by_phone || ""}<br />{beneficiary.referred_by_note || ""}</p></div>
    </section>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[
      ["This Month", summary.thisMonth], ["This Year", summary.thisYear], ["Last 12 Months", summary.last12Months], ["Lifetime", summary.lifetime], ["Payment Count", summary.paymentCount], ["Last Payment", summary.lastPaymentDate],
    ].map(([label, value]) => <div key={label as string} className="rounded-xl border bg-[var(--surface)] p-4"><p className="text-xs uppercase text-[var(--muted-text)]">{label}</p><strong>{label === "Payment Count" ? value : label === "Last Payment" ? date(value as string | null) : money(Number(value))}</strong></div>)}</section>
    <section className="mb-5 grid gap-5 xl:grid-cols-2">
      <form action={saveDonationMonthlySupportAction.bind(null, beneficiary.id)} className="grid gap-3 rounded-xl border bg-[var(--surface)] p-5 md:grid-cols-2"><h2 className="text-xl font-semibold md:col-span-2">Monthly Support</h2><label className="flex items-center gap-2 font-medium md:col-span-2"><input type="checkbox" name="monthly_support_enabled" defaultChecked={beneficiary.monthly_support_enabled} /> Enabled</label><label className="grid gap-1 text-sm">Amount<input className={input} name="default_monthly_amount" type="number" min="0.01" step="0.01" defaultValue={beneficiary.default_monthly_amount ?? ""} /></label><label className="grid gap-1 text-sm">Reminder Day<input className={input} name="reminder_day_of_month" type="number" min="1" max="28" defaultValue={beneficiary.reminder_day_of_month ?? ""} /></label><label className="grid gap-1 text-sm">Start<input className={input} name="support_start_date" type="date" defaultValue={beneficiary.support_start_date ?? ""} /></label><label className="grid gap-1 text-sm">End<input className={input} name="support_end_date" type="date" defaultValue={beneficiary.support_end_date ?? ""} /></label><label className="grid gap-1 text-sm">Category<select className={input} name="default_category_id" defaultValue={beneficiary.default_category_id ?? ""}><option value="">Not specified</option>{options.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm">Payment Method<select className={input} name="default_payment_method_id" defaultValue={beneficiary.default_payment_method_id ?? ""}><option value="">Not specified</option>{options.paymentMethods.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm md:col-span-2">Purpose<input className={input} name="default_purpose" defaultValue={beneficiary.default_purpose ?? ""} /></label><div className="md:col-span-2"><button className="rounded-lg bg-[var(--primary)] px-4 py-2 font-semibold text-[var(--primary-foreground)]">Save Settings</button></div></form>
      <div className="rounded-xl border bg-[var(--surface)] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-semibold">Monthly Giving Trend</h2><form><select name="period" defaultValue={period} className={input}><option value="3m">Last 3 Months</option><option value="12m">Last 12 Months</option><option value="1y">1 Year</option><option value="3y">3 Years</option><option value="custom">Custom</option></select><button className="ml-2 rounded-lg border px-3 py-2">Apply</button></form></div>{period === "custom" ? <form className="mt-3 flex gap-2"><input type="hidden" name="period" value="custom" /><input name="from" type="date" defaultValue={query.from} className={input} /><input name="to" type="date" defaultValue={query.to} className={input} /><button className="rounded-lg border px-3">Show</button></form> : null}<div className="mt-5 flex min-h-48 items-end gap-2 overflow-x-auto border-b border-l p-3">{trend.map((item) => <div key={item.month} className="flex min-w-14 flex-1 flex-col items-center justify-end gap-1"><span className="text-xs">{Math.round(item.amount).toLocaleString()}</span><div title={money(item.amount)} className="w-full rounded-t bg-[var(--primary)]" style={{ height: `${Math.max(8, (item.amount / max) * 140)}px` }} /><span className="text-[10px] text-[var(--muted-text)]">{item.month}</span></div>)}{!trend.length ? <p className="m-auto text-sm text-[var(--muted-text)]">No completed donations in this period.</p> : null}</div></div>
    </section>
    <section className="rounded-xl border bg-[var(--surface)] p-5"><h2 className="mb-4 text-xl font-semibold">Payment History</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Date</th><th className="p-2">Category</th><th className="p-2">Amount</th><th className="p-2">Method</th><th className="p-2">Purpose</th><th className="p-2">Status</th><th className="p-2">Proof</th><th className="p-2">Open</th></tr></thead><tbody>{expenses.map((item) => <tr key={item.id} className="border-b last:border-0"><td className="p-2">{date(item.donation_date)}</td><td className="p-2">{item.category?.name}</td><td className="p-2">{money(Number(item.amount))}</td><td className="p-2">{item.payment_method?.name}</td><td className="p-2">{item.purpose}</td><td className="p-2">{item.status}</td><td className="p-2">{item.proof_path ? "Uploaded" : "—"}</td><td className="p-2"><Link href={`/admin/donation-expenses/${item.id}`} className="font-semibold text-[var(--primary)]">Open / Voucher</Link></td></tr>)}</tbody></table></div></section>
  </DashboardShell>;
}
