import { connection } from "next/server";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { getCustomerSalesHistory } from "@/lib/sales/data";
import { dateTime,label,money } from "@/lib/orders/types";
export const dynamic="force-dynamic";
export default async function AdminCustomerSales({params}:{params:Promise<{id:string}>}){await connection();await requirePermission("sales.view_all");const{id}=await params,{data:customer}=await createSupabaseAdminClient().from("profiles").select("id,full_name,email,role").eq("id",id).maybeSingle();if(!customer||customer.role!=="customer")notFound();const data=await getCustomerSalesHistory(id),total=data.orders.reduce((n,x)=>n+Number(x.total_amount),0),paid=data.orders.reduce((n,x)=>n+Number(x.paid_amount),0);return <DashboardShell admin title={`${customer.full_name||customer.email} · Sales`} subtitle="Customer purchases, payments, outstanding balances, products and assigned serials."><a href={`/admin/users/${id}`} className="font-semibold text-[var(--primary)]">← Customer profile</a><section className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{[["Purchases",data.orders.length],["Total value",money(total)],["Paid",money(paid)],["Outstanding",money(Math.max(total-paid,0))]].map(([name,value])=><article key={name} className="rounded-xl border bg-[var(--surface)] p-4"><p className="text-sm text-[var(--muted-text)]">{name}</p><b className="text-xl">{value}</b></article>)}</section><div className="mt-4 overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr><th className="p-3">Sale</th><th>Status</th><th>Payment</th><th>Total</th><th>Paid</th><th>Date</th></tr></thead><tbody>{data.orders.map(order=><tr key={order.id} className="border-t"><td className="p-3"><a href={`/admin/sales/${order.id}`} className="font-bold">{order.order_number}</a></td><td>{label(order.status)}</td><td>{label(order.payment_status)}</td><td>{money(order.total_amount,order.currency)}</td><td>{money(order.paid_amount,order.currency)}</td><td>{dateTime(order.created_at)}</td></tr>)}</tbody></table></div></DashboardShell>}
