import { connection } from "next/server";
import { HrPage, hrCard, hrField, hrPrimary, hrSecondary, relation } from "@/components/hr/HrPage";
import { getHrEmployees, getHrPayroll } from "@/lib/hr/operational";
import { savePayrollAction, updatePayrollStatusAction } from "../hr-actions";

export const dynamic = "force-dynamic";

export default async function PayrollPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await connection();
  const [rows, employees, params] = await Promise.all([getHrPayroll(),getHrEmployees({pageSize:100,status:"all"}),searchParams]);
  return <HrPage title="Payroll" subtitle="Prepare, approve and mark employee payroll as paid in BDT." success={params.success} error={params.error}>
    <form action={savePayrollAction} className={hrCard}><input type="hidden" name="return_to" value="/admin/hr/payroll"/><h2 className="font-semibold">Create payroll record</h2><div className="mt-3 grid gap-3 md:grid-cols-3 xl:grid-cols-6"><label className="text-sm font-semibold">Employee<select name="employee_record_id" required className={hrField}><option value="">Select employee</option>{employees.rows.map(e=><option key={e.id} value={e.id}>{relation(e.profiles)?.full_name||e.employee_number}</option>)}</select></label><label className="text-sm font-semibold">Period start<input type="date" name="period_start" required className={hrField}/></label><label className="text-sm font-semibold">Period end<input type="date" name="period_end" required className={hrField}/></label><label className="text-sm font-semibold">Base salary<input type="number" min="0" step=".01" name="base_salary" required className={hrField}/></label><label className="text-sm font-semibold">Allowance<input type="number" min="0" step=".01" name="allowance" defaultValue="0" className={hrField}/></label><label className="text-sm font-semibold">Bonus<input type="number" min="0" step=".01" name="bonus" defaultValue="0" className={hrField}/></label><label className="text-sm font-semibold">Deduction<input type="number" min="0" step=".01" name="deduction" defaultValue="0" className={hrField}/></label><label className="text-sm font-semibold">Currency<input name="currency" defaultValue="BDT" maxLength={3} className={hrField}/></label><label className="text-sm font-semibold md:col-span-2">Notes<input name="notes" className={hrField}/></label></div><button className={`${hrPrimary} mt-3`}>Create draft payroll</button></form>
    <section className="mt-5 space-y-3">{rows.map(row=>{const employee=relation(row.hr_employee_records);const person=employee?relation(employee.profiles):null;return <article key={row.id} className={`${hrCard} flex flex-wrap items-center justify-between gap-4`}><div><strong>{person?.full_name||employee?.employee_number}</strong><p className="text-sm text-[var(--muted-text)]">{row.period_start} to {row.period_end} · Gross {row.currency} {row.gross_pay} · Net {row.currency} {row.net_pay}</p></div><div className="flex items-center gap-2"><span className="capitalize">{row.status}</span>{row.status==="draft"?<form action={updatePayrollStatusAction}><input type="hidden" name="payroll_id" value={row.id}/><input type="hidden" name="return_to" value="/admin/hr/payroll"/><button name="status" value="approved" className={hrPrimary}>Approve</button></form>:null}{row.status==="approved"?<form action={updatePayrollStatusAction}><input type="hidden" name="payroll_id" value={row.id}/><input type="hidden" name="return_to" value="/admin/hr/payroll"/><button name="status" value="paid" className={hrPrimary}>Mark paid</button></form>:null}{!["paid","cancelled"].includes(row.status)?<form action={updatePayrollStatusAction}><input type="hidden" name="payroll_id" value={row.id}/><input type="hidden" name="return_to" value="/admin/hr/payroll"/><button name="status" value="cancelled" className={hrSecondary}>Cancel</button></form>:null}</div></article>})}{!rows.length?<p className={hrCard}>No payroll records yet.</p>:null}</section>
  </HrPage>;
}
