"use client";

import Image from "next/image";
import Link from "next/link";
import { useActionState, useState } from "react";
import { loginAction, registerAction, updateOwnProfileAction } from "@/lib/auth/actions";
import { countries } from "@/lib/data/countries";
import type { Profile } from "@/lib/auth/types";

const initialState = { message: "" };
function PasswordField({ name, label }: { name: string; label: string }) {
  const [show, setShow] = useState(false);
  return <div><label className="text-sm font-semibold" htmlFor={name}>{label}</label><div className="mt-1 flex rounded-lg border border-[var(--border)] bg-[var(--surface)]"><input id={name} name={name} type={show ? "text" : "password"} required minLength={8} className="min-w-0 flex-1 bg-transparent px-3 py-2 outline-none"/><button type="button" onClick={() => setShow(!show)} className="px-3 text-sm font-semibold text-[var(--muted-text)]">{show ? "Hide" : "Show"}</button></div></div>;
}
function Logo() { return <Image src="/brand/sen-logo.svg" alt="SEN — Shenzhen Energy & Networks" width={180} height={76} className="h-auto w-40" priority />; }

export function LoginForm({ blocked }: { blocked?: boolean }) {
  const [state, action, pending] = useActionState(loginAction, initialState);
  return <form action={action} className="mx-auto max-w-md space-y-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-8 shadow-sm"><Logo/><div><h1 className="text-3xl font-bold">Sign in to SEN</h1><p className="mt-2 text-sm text-[var(--muted-text)]">Access your account dashboard securely.</p></div>{blocked ? <p className="rounded-lg border border-[var(--warning)] p-3 text-sm">Your account is suspended or disabled. Contact SEN administration for help.</p> : null}{state.message ? <p className="rounded-lg bg-[var(--muted-surface)] p-3 text-sm">{state.message}</p> : null}<div><label htmlFor="email" className="text-sm font-semibold">Email</label><input id="email" name="email" type="email" autoComplete="email" required className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></div><PasswordField name="password" label="Password"/><button disabled={pending} className="w-full rounded-lg bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)] disabled:opacity-60">{pending ? "Signing in..." : "Sign in"}</button><div className="flex justify-between text-sm"><Link href="/register">Create account</Link><Link href="/forgot-password">Forgot password?</Link></div></form>;
}

export function RegisterForm() {
  const [state, action, pending] = useActionState(registerAction, initialState);
  const [type, setType] = useState("individual");
  return <form action={action} className="mx-auto max-w-2xl space-y-5 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-8 shadow-sm"><Logo/><div><h1 className="text-3xl font-bold">Create your SEN account</h1><p className="mt-2 text-sm text-[var(--muted-text)]">All public registrations create standard customer accounts. Administrators manage employee and admin roles later.</p></div>{state.message ? <p className="rounded-lg bg-[var(--muted-surface)] p-3 text-sm">{state.message}</p> : null}<div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-semibold" htmlFor="fullName">Full name</label><input id="fullName" name="fullName" required minLength={2} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></div><div><label className="text-sm font-semibold" htmlFor="email">Email</label><input id="email" name="email" type="email" required className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></div><div><label className="text-sm font-semibold" htmlFor="phone">Phone number</label><input id="phone" name="phone" className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></div><div><label className="text-sm font-semibold" htmlFor="countryCode">Country</label><select id="countryCode" name="countryCode" defaultValue="BD" className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2">{countries.map(c => <option key={c.code} value={c.code}>{c.name}</option>)}</select></div><PasswordField name="password" label="Password"/><PasswordField name="confirmPassword" label="Confirm password"/><div><label className="text-sm font-semibold" htmlFor="customerType">Customer type</label><select id="customerType" name="customerType" value={type} onChange={(e) => setType(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2"><option value="individual">Individual</option><option value="company">Company</option></select></div>{type === "company" ? <div><label className="text-sm font-semibold" htmlFor="companyName">Company name</label><input id="companyName" name="companyName" className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></div> : null}</div><label className="flex gap-3 text-sm"><input name="agreement" type="checkbox" required/> <span>I agree to SEN terms and privacy placeholders.</span></label><button disabled={pending} className="w-full rounded-lg bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)] disabled:opacity-60">{pending ? "Creating account..." : "Create customer account"}</button><p className="text-sm">Already registered? <Link href="/login">Sign in</Link></p></form>;
}

export function ProfileForm({ profile }: { profile: Profile }) {
  const [state, action, pending] = useActionState(updateOwnProfileAction, initialState);
  const [type, setType] = useState(profile.customer_type);
  return <form action={action} className="space-y-4 rounded-2xl border border-[var(--border)] p-6"><h2 className="text-xl font-bold">Profile</h2>{state.message ? <p className="rounded-lg bg-[var(--muted-surface)] p-3 text-sm">{state.message}</p> : null}<div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Full name<input name="fullName" defaultValue={profile.full_name} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></label><label className="text-sm font-semibold">Email<input value={profile.email} disabled className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--muted-surface)] px-3 py-2"/></label><label className="text-sm font-semibold">Phone<input name="phone" defaultValue={profile.phone ?? ""} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></label><label className="text-sm font-semibold">Country<select name="countryCode" defaultValue={profile.country_code} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2">{countries.map(c => <option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="text-sm font-semibold">Customer type<select name="customerType" value={type} onChange={(e) => setType(e.target.value as "individual" | "company")} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 py-2"><option value="individual">Individual</option><option value="company">Company</option></select></label>{type === "company" ? <label className="text-sm font-semibold">Company name<input name="companyName" defaultValue={profile.company_name ?? ""} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></label> : null}<label className="text-sm font-semibold md:col-span-2">Avatar URL<input name="avatarUrl" defaultValue={profile.avatar_url ?? ""} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-transparent px-3 py-2"/></label></div><p className="text-sm text-[var(--muted-text)]">Role and status are protected fields and cannot be changed here.</p><button disabled={pending} className="rounded-lg bg-[var(--primary)] px-4 py-2 font-semibold text-[var(--primary-foreground)]">Save profile</button></form>;
}
