import { connection } from "next/server";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { ActivityForm, LeadStatusForm } from "@/components/crm/CrmForms";
import { CreateFollowupForm, DoNotContactForm, FollowupActionForms } from "@/components/crm/FollowupForms";
import { requirePermission } from "@/lib/auth/permissions";
import { getCrmFollowupsForLead, getCrmFollowupStaff, getCrmLead } from "@/lib/crm/data";
import { classifyFollowup, formatCrmDateTime } from "@/lib/crm/followups";

export const dynamic="force-dynamic";
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase());
export default async function CrmLeadPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string;error?:string}>}) {
  await connection(); const {id}=await params; const query=await searchParams; const {profile,permissions}=await requirePermission("crm.view"); const data=await getCrmLead(id); if(!data.lead)notFound();
  const lead=data.lead; const company=lead.crm_companies as unknown as {id:string;name:string;email:string|null;phone:string|null;country_name:string|null}|null; const contact=lead.crm_contacts as unknown as {id:string;full_name:string;email:string|null;phone:string|null}|null; const assignee=lead.profiles as unknown as {full_name:string|null;email:string}|null;
  const canEdit=profile.role==="admin"||permissions.has("crm.edit");
  const canViewFollowups=profile.role==="admin"||permissions.has("crm.followups_view");
  const canViewAll=profile.role==="admin"||permissions.has("crm.followups_view_all");
  const canCreateFollowup=profile.role==="admin"||permissions.has("crm.followups_create");
  const canEditFollowup=profile.role==="admin"||permissions.has("crm.followups_edit");
  const canCompleteFollowup=profile.role==="admin"||permissions.has("crm.followups_complete");
  const canAssignFollowup=profile.role==="admin"||permissions.has("crm.followups_assign");
  const [followups,staff]=canViewFollowups?await Promise.all([getCrmFollowupsForLead(id,profile.id,canViewAll),getCrmFollowupStaff()]):[[],[]];
  const activeFollowup=followups.find((item)=>["active","waiting_customer"].includes(item.status));
  const returnTo=`/admin/crm/leads/${id}`;
  return <DashboardShell admin={profile.role==="admin"} employeePermissions={profile.role==="employee"?permissions:undefined} title={lead.title} subtitle={`${lead.lead_number} · ${title(lead.status)} · ${title(lead.priority)} priority`}>
    {query.success?<p className="mb-3 rounded-lg border border-green-200 bg-green-50 p-3 text-green-900">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3 text-red-900">{query.error}</p>:null}
    <div className="mb-3 flex flex-wrap gap-2"><a href="/admin/crm" className="rounded-lg border px-3 py-2 font-bold">← CRM overview</a>{canViewFollowups?<a href="/admin/crm/follow-ups" className="rounded-lg border px-3 py-2 font-bold">Follow-up workspace</a>:null}</div>
    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border bg-[var(--surface)] p-4 lg:col-span-2"><h2 className="text-lg font-bold">Opportunity</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-[var(--muted-text)]">Company</dt><dd>{company?.name??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Contact</dt><dd>{contact?.full_name??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Value</dt><dd className="font-bold">{lead.currency} {Number(lead.estimated_value).toLocaleString("en-BD")}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Owner</dt><dd>{assignee?.full_name??assignee?.email??"Unassigned"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Expected close</dt><dd>{lead.expected_close_date??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Source</dt><dd>{title(lead.source)}</dd></div></dl><p className="mt-4 whitespace-pre-wrap">{lead.description||"No description."}</p></section><section className="rounded-2xl border bg-[var(--surface)] p-4"><h2 className="mb-3 text-lg font-bold">Stage</h2>{canEdit?<LeadStatusForm leadId={id} current={lead.status}/>:<p>{title(lead.status)}</p>}</section></div>
    {canViewFollowups?<section className="mt-4 rounded-2xl border bg-[var(--surface)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-bold">Follow-up</h2><p className="text-sm text-[var(--muted-text)]">Permanent contact plan and current customer context.</p></div>{activeFollowup?<span className="rounded-full border px-3 py-1 text-sm font-bold">{title(classifyFollowup({status:activeFollowup.status,nextFollowupAt:activeFollowup.next_follow_up_at}))}</span>:null}</div>
      {activeFollowup?<div className="mt-4 grid gap-4 xl:grid-cols-[1fr_18rem]"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-xs text-[var(--muted-text)]">Last contact</dt><dd>{formatCrmDateTime(activeFollowup.last_contact_at)}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Next follow-up</dt><dd className="font-bold">{formatCrmDateTime(activeFollowup.next_follow_up_at)}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Reason</dt><dd>{title(activeFollowup.reason)}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Preferred channel</dt><dd>{title(activeFollowup.preferred_channel)}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Priority</dt><dd>{title(activeFollowup.priority)}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Status</dt><dd>{title(activeFollowup.status)}</dd></div><div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs text-[var(--muted-text)]">Instruction</dt><dd className="whitespace-pre-wrap">{activeFollowup.instruction}</dd></div><div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs text-[var(--muted-text)]">Customer interest</dt><dd className="whitespace-pre-wrap">{activeFollowup.interest_summary??"—"}</dd></div><div className="sm:col-span-2 lg:col-span-3"><dt className="text-xs text-[var(--muted-text)]">Conversation summary</dt><dd className="whitespace-pre-wrap">{activeFollowup.conversation_summary??"—"}</dd></div></dl><FollowupActionForms followup={activeFollowup} staff={staff} canEdit={canEditFollowup} canComplete={canCompleteFollowup} canAssign={canAssignFollowup} returnTo={returnTo}/></div>:canCreateFollowup&&!lead.do_not_contact?<details className="mt-4" open><summary className="font-bold">Add follow-up</summary><div className="mt-3"><CreateFollowupForm leadId={id} staff={staff} canAssign={canAssignFollowup} returnTo={returnTo}/></div></details>:<p className="mt-4 text-[var(--muted-text)]">{lead.do_not_contact?"Follow-ups are disabled because Do Not Contact is enabled.":"No active follow-up."}</p>}
      {canEditFollowup?<details className="mt-4 rounded-xl border p-3"><summary className="font-bold text-red-800">Contact restriction</summary><div className="mt-3"><DoNotContactForm leadId={id} enabled={lead.do_not_contact} reason={lead.do_not_contact_reason} returnTo={returnTo}/></div></details>:null}
    </section>:null}
    <section id="followup-history" className="mt-4 rounded-2xl border bg-[var(--surface)] p-4"><h2 className="mb-3 text-lg font-bold">Activity timeline</h2>{canEdit?<ActivityForm leadId={id} companyId={lead.company_id} contactId={lead.contact_id}/>:null}<div className="mt-4 grid gap-2">{data.activities.map(item=>{const actor=item.profiles as unknown as {full_name:string|null;email:string}|null;return <article key={item.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{title(item.activity_type)} · {item.subject}</strong><time className="text-xs text-[var(--muted-text)]">{formatCrmDateTime(item.created_at)}</time></div><p className="mt-1 whitespace-pre-wrap">{item.details||"No details."}</p>{item.customer_response?<p className="mt-2 rounded-lg bg-[var(--muted-surface)] p-2"><strong>Customer response:</strong> {item.customer_response}</p>:null}{item.outcome?<p className="mt-1"><strong>Outcome:</strong> {item.outcome}</p>:null}{item.previous_due_at&&item.next_follow_up_at?<p className="mt-1 text-sm"><strong>Rescheduled:</strong> {formatCrmDateTime(item.previous_due_at)} → {formatCrmDateTime(item.next_follow_up_at)}</p>:item.next_follow_up_at?<p className="mt-1 text-sm"><strong>Next follow-up:</strong> {formatCrmDateTime(item.next_follow_up_at)}</p>:null}{item.next_instruction?<p className="text-sm"><strong>Next instruction:</strong> {item.next_instruction}</p>:null}<small className="text-[var(--muted-text)]">By {actor?.full_name??actor?.email??"Staff"}{item.communication_channel?` · ${title(item.communication_channel)}`:""}{item.direction?` · ${title(item.direction)}`:""}{item.completed_at?" · Completed":item.due_at?` · Due ${formatCrmDateTime(item.due_at)}`:""}</small></article>})}{!data.activities.length?<p className="text-[var(--muted-text)]">No activity recorded yet.</p>:null}</div></section>
  </DashboardShell>;
}
