import { connection } from "next/server";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { ActivityForm, LeadStatusForm } from "@/components/crm/CrmForms";
import { requirePermission } from "@/lib/auth/permissions";
import { getCrmLead } from "@/lib/crm/data";

export const dynamic="force-dynamic";
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,l=>l.toUpperCase());
export default async function CrmLeadPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string;error?:string}>}) {
  await connection(); const {id}=await params; const query=await searchParams; const {profile,permissions}=await requirePermission("crm.view"); const data=await getCrmLead(id); if(!data.lead)notFound();
  const lead=data.lead; const company=lead.crm_companies as unknown as {id:string;name:string;email:string|null;phone:string|null;country_name:string|null}|null; const contact=lead.crm_contacts as unknown as {id:string;full_name:string;email:string|null;phone:string|null}|null; const assignee=lead.profiles as unknown as {full_name:string|null;email:string}|null;
  const canEdit=profile.role==="admin"||permissions.has("crm.edit");
  return <DashboardShell admin={profile.role==="admin"} employeePermissions={profile.role==="employee"?permissions:undefined} title={lead.title} subtitle={`${lead.lead_number} · ${title(lead.status)} · ${title(lead.priority)} priority`}>
    {query.success?<p className="mb-3 rounded-lg border border-green-200 bg-green-50 p-3 text-green-900">{query.success}</p>:null}{query.error?<p className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3 text-red-900">{query.error}</p>:null}
    <a href="/admin/crm" className="mb-3 inline-block rounded-lg border px-3 py-2 font-bold">← CRM overview</a>
    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border bg-[var(--surface)] p-4 lg:col-span-2"><h2 className="text-lg font-bold">Opportunity</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-[var(--muted-text)]">Company</dt><dd>{company?.name??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Contact</dt><dd>{contact?.full_name??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Value</dt><dd className="font-bold">{lead.currency} {Number(lead.estimated_value).toLocaleString("en-BD")}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Owner</dt><dd>{assignee?.full_name??assignee?.email??"Unassigned"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Expected close</dt><dd>{lead.expected_close_date??"—"}</dd></div><div><dt className="text-xs text-[var(--muted-text)]">Source</dt><dd>{title(lead.source)}</dd></div></dl><p className="mt-4 whitespace-pre-wrap">{lead.description||"No description."}</p></section><section className="rounded-2xl border bg-[var(--surface)] p-4"><h2 className="mb-3 text-lg font-bold">Stage</h2>{canEdit?<LeadStatusForm leadId={id} current={lead.status}/>:<p>{title(lead.status)}</p>}</section></div>
    <section className="mt-4 rounded-2xl border bg-[var(--surface)] p-4"><h2 className="mb-3 text-lg font-bold">Activity timeline</h2>{canEdit?<ActivityForm leadId={id} companyId={lead.company_id} contactId={lead.contact_id}/>:null}<div className="mt-4 grid gap-2">{data.activities.map(item=>{const actor=item.profiles as unknown as {full_name:string|null;email:string}|null;return <article key={item.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{title(item.activity_type)} · {item.subject}</strong><time className="text-xs text-[var(--muted-text)]">{new Date(item.created_at).toLocaleString("en-BD")}</time></div><p className="mt-1 whitespace-pre-wrap">{item.details||"No details."}</p><small className="text-[var(--muted-text)]">By {actor?.full_name??actor?.email??"Staff"}{item.completed_at?" · Completed":item.due_at?` · Due ${new Date(item.due_at).toLocaleString("en-BD")}`:""}</small></article>})}{!data.activities.length?<p className="text-[var(--muted-text)]">No activity recorded yet.</p>:null}</div></section>
  </DashboardShell>;
}
