"use client";

import { useState } from "react";
import { saveAndReviewRecruitmentJobAction, saveRecruitmentJobDraftAction } from "@/app/employee/hr/recruitment/application/actions";

type Row = Record<string, string | boolean> & { id: string };
type Props = { application:any; education:any[]; experience:any[]; qualifications:any[]; skills:any[]; documents:any[]; success?:string; error?:string; validationErrors?:Record<string,string> };
const id=()=>crypto.randomUUID();
const inputClass="w-full rounded-lg border px-3 py-2";
const sectionClass="space-y-4 rounded-2xl border bg-[var(--surface)] p-5 shadow-sm";

function Field({label,name,type="text",defaultValue,required=false}:{label:string;name:string;type?:string;defaultValue?:string;required?:boolean}) { return <label className="block text-sm font-semibold">{label}{required?" *":""}<input className={inputClass} name={name} type={type} defaultValue={defaultValue??""}/></label>; }
function RowEditor({title,rows,setRows,kind}:{title:string;rows:Row[];setRows:(rows:Row[])=>void;kind:"education"|"experience"|"qualification"|"skill"}) {
  const definitions={education:[["degree","Degree / Certificate"],["institution","Institution Name"],["subject","Subject / Group / Major"],["result","Result / Grade / CGPA"],["completionYear","Passing / Completion Year"]],experience:[["company","Company / Organization"],["designation","Designation"],["fromDate","From Date"],["toDate","To Date"],["responsibilities","Responsibilities / Experience Summary"]],qualification:[["name","Qualification / Certificate / Training Name"],["institution","Institution / Issuing Organization"],["subject","Subject / Area"],["completionYear","Completion Year"],["details","Additional Details"]],skill:[["name","Skill Name"],["proficiency","Proficiency"],["details","Details"]]}[kind];
  return <div className="space-y-4"><div className="flex items-center justify-between"><h3 className="font-bold">{title}</h3><button type="button" className="rounded-lg border px-3 py-2" onClick={()=>setRows([...rows,{id:id()}])}>+ Add Another</button></div>{rows.map((row,index)=><div key={row.id} className="rounded-xl border p-4"><div className="grid gap-3 md:grid-cols-2">{definitions.map(([key,label])=>key==="proficiency"?<label key={key} className="text-sm font-semibold">{label}<select className={inputClass} value={String(row[key]??"")} onChange={(e)=>setRows(rows.map((r,i)=>i===index?{...r,[key]:e.target.value}:r))}><option value="">Optional</option><option>Basic</option><option>Intermediate</option><option>Advanced</option><option>Expert</option></select></label>:<label key={key} className="text-sm font-semibold">{label}<input className={inputClass} type={key.toLowerCase().includes("date")?"date":"text"} value={String(row[key]??"")} onChange={(e)=>setRows(rows.map((r,i)=>i===index?{...r,[key]:e.target.value}:r))}/></label>)}</div>{kind==="experience"?<label className="mt-3 flex gap-2"><input type="checkbox" checked={Boolean(row.currentlyWorking)} onChange={(e)=>setRows(rows.map((r,i)=>i===index?{...r,currentlyWorking:e.target.checked}:r))}/>Currently Working Here</label>:null}{kind!=="skill"?<label className="mt-3 block text-sm font-semibold">{kind==="education"?"Educational Certificate":kind==="experience"?"Experience Certificate (optional)":"Training Document (optional)"}<input className={inputClass} type="file" name={`${kind==="qualification"?"qualification_certificate":`${kind}_certificate`}:${row.id}`} accept=".pdf,.jpg,.jpeg,.png"/></label>:null}<button type="button" className="mt-3 text-sm font-bold text-red-700" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}>Remove</button></div>)}</div>;
}

export function RecruitmentJobApplicationForm(props:Props) {
  const a=props.application??{};
  const [marital,setMarital]=useState(a.marital_status??""); const [employment,setEmployment]=useState(a.employment_status??"");
  const [present,setPresent]=useState(a.present_address??""); const [permanent,setPermanent]=useState(a.permanent_address??"");
  const [education,setEducation]=useState<Row[]>(props.education.map((r)=>({id:r.id,degree:r.degree??"",institution:r.institution??"",subject:r.subject??"",result:r.result??"",completionYear:String(r.completion_year??"")})));
  const [experience,setExperience]=useState<Row[]>(props.experience.map((r)=>({id:r.id,company:r.company??"",designation:r.designation??"",fromDate:r.from_date??"",toDate:r.to_date??"",currentlyWorking:r.currently_working,responsibilities:r.responsibilities??""})));
  const [qualifications,setQualifications]=useState<Row[]>(props.qualifications.map((r)=>({id:r.id,name:r.qualification_name??"",institution:r.institution??"",subject:r.subject??"",completionYear:String(r.completion_year??""),details:r.details??""})));
  const [skills,setSkills]=useState<Row[]>(props.skills.map((r)=>({id:r.id,name:r.skill_name??"",proficiency:r.proficiency??"",details:r.details??""})));
  return <form encType="multipart/form-data" className="space-y-5">
    <input type="hidden" name="education_json" value={JSON.stringify(education)}/><input type="hidden" name="experience_json" value={JSON.stringify(experience)}/><input type="hidden" name="qualifications_json" value={JSON.stringify(qualifications)}/><input type="hidden" name="skills_json" value={JSON.stringify(skills)}/>
    {props.success?<p className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{props.success}</p>:null}{props.error?<p className="rounded-xl bg-red-50 p-3 text-red-800">{props.error}</p>:null}
    {Object.keys(props.validationErrors??{}).length?<section className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-900"><h2 className="font-bold">Please correct these items before submitting:</h2><ul className="mt-2 list-disc space-y-1 pl-5">{Object.entries(props.validationErrors??{}).map(([field,message])=><li key={field}>{message}</li>)}</ul></section>:null}
    <section className={sectionClass}><h2 className="text-xl font-bold">Personal Information</h2><div className="grid gap-3 md:grid-cols-2"><Field label="Full Name" name="full_name" defaultValue={a.full_name}/><Field label="Father's Name" name="father_name" defaultValue={a.father_name}/><Field label="Mother's Name" name="mother_name" defaultValue={a.mother_name}/><Field label="Date of Birth" name="date_of_birth" type="date" defaultValue={a.date_of_birth}/><Field label="Gender" name="gender" defaultValue={a.gender}/><label className="text-sm font-semibold">Marital Status<select className={inputClass} name="marital_status" value={marital} onChange={(e)=>setMarital(e.target.value)}><option value="">Select</option><option>Single</option><option>Married</option><option>Other</option></select></label>{marital==="Married"?<><Field label="Spouse Name" name="spouse_name" defaultValue={a.spouse_name}/><Field label="Spouse Contact Number" name="spouse_contact_number" defaultValue={a.spouse_contact_number}/></>:null}<Field label="Nationality" name="nationality" defaultValue={a.nationality}/><Field label="Phone" name="phone" defaultValue={a.phone}/><Field label="Email" name="email" type="email" defaultValue={a.email}/><Field label="Emergency Contact Name" name="emergency_contact_name" defaultValue={a.emergency_contact_name}/><Field label="Emergency Contact Phone" name="emergency_contact_phone" defaultValue={a.emergency_contact_phone}/><Field label="Emergency Contact Relationship" name="emergency_contact_relationship" defaultValue={a.emergency_contact_relationship}/></div><label className="block text-sm font-semibold">Present Address<textarea className={inputClass} name="present_address" value={present} onChange={(e)=>setPresent(e.target.value)}/></label><label className="block text-sm font-semibold">Permanent Address<textarea className={inputClass} name="permanent_address" value={permanent} onChange={(e)=>setPermanent(e.target.value)}/></label><button type="button" className="rounded-lg border px-3 py-2" onClick={()=>setPermanent(present)}>Same as Present Address</button></section>
    <section className={sectionClass}><h2 className="text-xl font-bold">Identity</h2><div className="grid gap-3 md:grid-cols-2"><Field label="NID Number" name="nid_number" defaultValue={a.nid_number}/><Field label="Passport Number (optional)" name="passport_number" defaultValue={a.passport_number}/><Field label="Passport Expiry Date" name="passport_expiry_date" type="date" defaultValue={a.passport_expiry_date}/><Field label="NID Copy" name="nid_copy" type="file"/><Field label="Passport Copy" name="passport_copy" type="file"/><Field label="Recent Photograph (JPG/PNG)" name="photograph" type="file"/></div></section>
    <section id="employment-application" className={sectionClass}><h2 className="text-xl font-bold">Employment / Application</h2><div className="grid gap-3 md:grid-cols-2"><Field label="Position Applied For" name="position_applied_for" defaultValue={a.position_applied_for}/><Field label="Preferred / Available Joining Date" name="preferred_joining_date" type="date" defaultValue={a.preferred_joining_date}/><label className="text-sm font-semibold">Current Employment Status<select className={inputClass} name="employment_status" value={employment} onChange={(e)=>setEmployment(e.target.value)}><option value="">Select</option><option>Employed</option><option>Unemployed</option><option>Self-employed</option><option>Student</option><option>Other</option></select></label>{employment==="Employed"?<><Field label="Current Employer" name="current_employer" defaultValue={a.current_employer}/><Field label="Current Designation" name="current_designation" defaultValue={a.current_designation}/></>:null}<Field label="Expected Salary (optional)" name="expected_salary" type="number" defaultValue={a.expected_salary}/><Field label="Salary Currency" name="salary_currency" defaultValue={a.salary_currency??"BDT"}/><Field label="CV / Resume" name="cv" type="file"/></div><label className={`block text-sm font-semibold ${props.validationErrors?.introduction?"text-red-800":""}`}>Short Introduction / Reason for Applying<textarea className={`${inputClass} min-h-36 ${props.validationErrors?.introduction?"border-red-500 bg-red-50":""}`} name="introduction" defaultValue={a.introduction??""} minLength={100} maxLength={2000} aria-invalid={Boolean(props.validationErrors?.introduction)}/>{props.validationErrors?.introduction?<span className="mt-1 block text-sm text-red-700">{props.validationErrors.introduction}</span>:null}</label></section>
    <section className={sectionClass}><RowEditor title="Education" rows={education} setRows={setEducation} kind="education"/></section>
    <section className={sectionClass}><h2 className="text-xl font-bold">Work Experience</h2><label className="block">Do you have previous work experience? <select className={inputClass} name="has_experience" defaultValue={a.has_experience===true?"yes":a.has_experience===false?"no":""}><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select></label><RowEditor title="Experience Records" rows={experience} setRows={setExperience} kind="experience"/></section>
    <section className={sectionClass}><h2 className="text-xl font-bold">Professional Qualification / Training</h2><label className="block">Do you have any professional qualification, certification or training? <select className={inputClass} name="has_qualification" defaultValue={a.has_qualification===true?"yes":a.has_qualification===false?"no":""}><option value="">Select</option><option value="yes">Yes</option><option value="no">No</option></select></label><RowEditor title="Qualification / Training Records" rows={qualifications} setRows={setQualifications} kind="qualification"/></section>
    <section className={sectionClass}><RowEditor title="Skills (optional)" rows={skills} setRows={setSkills} kind="skill"/></section>
    <section className={sectionClass}><h2 className="text-xl font-bold">Other Supporting Documents</h2><Field label="Document title" name="other_document_title"/><label className="block text-sm font-semibold">Files<input className={inputClass} type="file" name="other_documents" multiple accept=".pdf,.jpg,.jpeg,.png"/></label><div><h3 className="font-bold">Document Center</h3>{props.documents.length?<ul className="mt-2 list-disc pl-5">{props.documents.map((d)=><li key={d.id}><a className="underline" href={`/employee/hr/recruitment/application/documents/${d.id}`}>{d.title}: {d.original_name}</a></li>)}</ul>:<p className="text-sm text-[var(--muted-text)]">No documents uploaded yet.</p>}</div></section>
    <div className="flex flex-wrap gap-3"><button formAction={saveRecruitmentJobDraftAction} className="rounded-xl border px-5 py-3 font-bold">Save Draft</button><button formAction={saveAndReviewRecruitmentJobAction} className="rounded-xl bg-[var(--primary)] px-5 py-3 font-bold text-[var(--primary-foreground)]">Save & Review</button></div>
  </form>;
}
