/* eslint-disable @next/next/no-html-link-for-pages */
import { connection } from "next/server";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

export default async function SerialsPage({ searchParams }: { searchParams: Promise<{ q?: string; product?: string; status?: string; warehouse?: string; page?: string }> }) {
  await connection();
  const { profile, permissions } = await requirePermission("serials.view");
  const params = await searchParams;
  const page = Math.max(1, Number(params.page) || 1), size = 30;
  const db = createSupabaseAdminClient();
  let query = db.from("serial_numbers").select("id,manufacturer_serial,sen_serial,barcode_value,product_id,variation_id,warehouse_id,status,condition,created_at", { count: "exact" }).order("created_at", { ascending: false }).range((page - 1) * size, page * size - 1);
  if (params.q?.trim()) query = query.or(`manufacturer_serial.ilike.%${params.q.trim()}%,sen_serial.ilike.%${params.q.trim()}%,barcode_value.ilike.%${params.q.trim()}%`);
  if (params.product) query = query.eq("product_id", params.product);
  if (params.status) query = query.eq("status", params.status);
  if (params.warehouse) query = query.eq("warehouse_id", params.warehouse);
  const [{ data: serials, count, error }, { data: warehouses }, { data: productOptions }] = await Promise.all([query, db.from("warehouses").select("id,code,name").eq("is_active", true).order("name"), db.from("products").select("id,name,sku").neq("status", "archived").order("name").limit(500)]);
  if (error) throw new Error("Unable to load serial numbers.");
  const productIds = [...new Set((serials ?? []).map((item) => item.product_id))];
  const { data: products } = productIds.length ? await db.from("products").select("id,name,sku").in("id", productIds) : { data: [] };
  const productMap = new Map((products ?? []).map((item) => [item.id, item]));
  const warehouseMap = new Map((warehouses ?? []).map((item) => [item.id, item]));
  const selectedProduct = params.product ? (productOptions ?? []).find((item) => item.id === params.product) : null;
  const expectedCount = (serials ?? []).filter((item) => item.status === "expected").length;
  return <DashboardShell admin={profile.role === "admin"} employeePermissions={profile.role === "employee" ? permissions : undefined} title="Serial Tracking" subtitle="Trace serialized SEN stock by product, warehouse, status, and movement history.">
    <div className="mb-5 flex flex-wrap gap-3"><a href="/admin/serials/generate" className="rounded bg-[var(--primary)] px-4 py-3 font-semibold text-[var(--primary-foreground)]">Generate / receive serials</a><a href="/admin/serials/scan" className="rounded border px-4 py-3 font-semibold">Scan or search</a><a href="/admin/serials/regenerate" className="rounded border px-4 py-3 font-semibold">Regenerate eligible</a><a href="/admin/serials/print" className="rounded border px-4 py-3 font-semibold">Print labels</a><a href="/admin/serials/batches" className="rounded border px-4 py-3 font-semibold">Generation batches</a><a href="/admin/serials/export" className="rounded border px-4 py-3 font-semibold">Export CSV</a></div>
    {selectedProduct ? <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-blue-950"><div><span className="text-xs font-bold uppercase tracking-wider">Filtered product</span><strong className="block">{selectedProduct.name}</strong><span className="text-sm">{selectedProduct.sku} · {count ?? 0} serial record(s)</span></div><div className="flex gap-2"><a href={`/admin/products/${selectedProduct.id}`} className="rounded border border-blue-300 bg-white px-3 py-2 font-semibold">Product details</a><a href="/admin/serials" className="rounded border border-blue-300 bg-white px-3 py-2 font-semibold">Clear filter</a></div></div> : null}
    {expectedCount ? <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><div><strong>{expectedCount} expected unit(s) are labels, not stock.</strong><p className="text-sm">Receive their generation batch to change the serial status to available and increase on-hand quantity.</p></div><a href={`/admin/serials/batches${params.product ? `?product=${params.product}` : ""}`} className="rounded bg-amber-900 px-4 py-2 font-semibold text-white">Review and receive batches</a></div> : null}
    <form className="mb-5 grid gap-3 rounded-xl border bg-[var(--surface)] p-4 sm:grid-cols-2 lg:grid-cols-5"><input name="q" aria-label="Search serials" placeholder="SEN or manufacturer serial" defaultValue={params.q} className="rounded border p-2" /><select name="product" defaultValue={params.product} className="rounded border p-2"><option value="">All products</option>{(productOptions ?? []).map((product) => <option key={product.id} value={product.id}>{product.name} ({product.sku})</option>)}</select><select name="status" defaultValue={params.status} className="rounded border p-2"><option value="">All statuses</option>{["expected","in_transit","received","available","reserved","allocated","packed","shipped","delivered","returned","quarantined","damaged","lost","transferred","disposed","voided","sold","unavailable","removed"].map((status) => <option key={status}>{status}</option>)}</select><select name="warehouse" defaultValue={params.warehouse} className="rounded border p-2"><option value="">All warehouses</option>{(warehouses ?? []).map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name} ({warehouse.code})</option>)}</select><button className="rounded border px-4 py-2 font-semibold">Apply filters</button></form>
    {serials?.length ? <div className="overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr><th className="p-3">SEN serial</th><th>Manufacturer serial</th><th>Product</th><th>Warehouse</th><th>Status</th><th>Condition</th><th>Registered</th></tr></thead><tbody>{serials.map((serial) => { const product = productMap.get(serial.product_id), warehouse = warehouseMap.get(serial.warehouse_id); return <tr key={serial.id} className="border-t"><td className="p-3"><a className="font-mono text-xs font-semibold" href={`/admin/serials/${serial.id}`}>{serial.sen_serial ?? serial.manufacturer_serial ?? "Open unit"}</a></td><td>{serial.manufacturer_serial ?? "Not provided"}</td><td>{product?.name ?? serial.product_id}<span className="block text-xs text-[var(--muted-text)]">{product?.sku}</span></td><td>{warehouse ? `${warehouse.name} (${warehouse.code})` : serial.warehouse_id ?? "Expected location not set"}</td><td>{serial.status}</td><td>{serial.condition}</td><td>{new Date(serial.created_at).toLocaleDateString()}</td></tr>; })}</tbody></table></div> : <p className="rounded-xl border bg-[var(--surface)] p-8 text-center text-[var(--muted-text)]">No serial numbers match these filters. Register serials while adding serialized stock.</p>}
    <p className="mt-4 text-sm">Page {page} - {count ?? 0} total serial numbers</p>
  </DashboardShell>;
}
