import { connection } from "next/server";
import { notFound } from "next/navigation";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requirePermission } from "@/lib/auth/permissions";
import { getPurchaseOrder } from "@/lib/purchasing/data";
import { transitionPurchaseOrderAction } from "../actions";

export const dynamic = "force-dynamic";
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());
const money=(value:number|string,currency:string)=>`${currency} ${Number(value).toLocaleString("en-BD",{minimumFractionDigits:2})}`;
export default async function PurchaseOrderPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string;error?:string}>}) {
  await connection(); const {profile,permissions}=await requirePermission("purchasing.view"); const {id}=await params; const messages=await searchParams; const data=await getPurchaseOrder(id); if(!data) notFound();
  const order=data.order; const supplier=order.suppliers as {id:string;name:string;code:string;email:string|null;phone:string|null}|null; const warehouse=order.warehouses as {code:string;name:string}|null;
  return <DashboardShell admin={profile.role==="admin"} employeePermissions={profile.role==="employee"?permissions:undefined} title={order.order_number} subtitle={`${supplier?.name ?? "Supplier"} → ${warehouse?.name ?? "Destination warehouse"}`}>
    {messages.success?<p className="mb-3 rounded-xl border border-green-200 bg-green-50 p-3 text-green-900">{messages.success}</p>:null}{messages.error?<p className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-red-900">{messages.error}</p>:null}
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["Status",label(order.status)],["Order date",order.order_date],["Expected",order.expected_delivery_date??"Not set"],["Total",money(order.total_amount,order.currency)],["Payment",label(order.payment_status)],["Supplier reference",order.supplier_reference??"—"],["Created",new Date(order.created_at).toLocaleString()],["Updated",new Date(order.updated_at).toLocaleString()]].map(([name,value])=><article key={name} className="rounded-xl border bg-[var(--surface)] p-3 shadow-sm"><p className="text-xs text-[var(--muted-text)]">{name}</p><p className="mt-1 font-bold">{value}</p></article>)}</section>
    <div className="my-3 flex flex-wrap gap-2">
      {order.status==="draft"?<><a href={`/admin/purchasing/${id}/edit`} className="rounded-xl border px-4 py-2.5 font-bold">Edit draft</a><form action={transitionPurchaseOrderAction.bind(null,id,"submit")}><button className="rounded-xl bg-[var(--primary)] px-4 py-2.5 font-bold text-[var(--primary-foreground)]">Submit for approval</button></form></>:null}
      {order.status==="pending_approval"?<form action={transitionPurchaseOrderAction.bind(null,id,"approve")}><button className="rounded-xl bg-emerald-700 px-4 py-2.5 font-bold text-white">Approve</button></form>:null}
      {order.status==="approved"?<form action={transitionPurchaseOrderAction.bind(null,id,"order")}><button className="rounded-xl bg-blue-700 px-4 py-2.5 font-bold text-white">Mark ordered</button></form>:null}
      {["ordered","partially_received"].includes(order.status)?<a href={`/admin/purchasing/${id}/receive`} className="rounded-xl bg-[var(--primary)] px-4 py-2.5 font-bold text-[var(--primary-foreground)]">Receive stock</a>:null}
      {order.status==="received"?<form action={transitionPurchaseOrderAction.bind(null,id,"close")}><button className="rounded-xl border px-4 py-2.5 font-bold">Close order</button></form>:null}
      {!["cancelled","received","closed"].includes(order.status)?<form action={transitionPurchaseOrderAction.bind(null,id,"cancel")}><button className="rounded-xl border border-red-300 px-4 py-2.5 font-bold text-red-700">Cancel</button></form>:null}
    </div>
    <section className="overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[var(--muted-surface)]"><tr>{["Product","SKU","Ordered","Received","Rejected","Unit cost","Line total"].map((head)=><th key={head} className="p-3">{head}</th>)}</tr></thead><tbody>{data.items.map((item)=><tr key={item.id} className="border-t"><td className="p-3 font-bold">{item.product_name_snapshot}</td><td className="p-3 font-mono text-xs">{item.sku_snapshot}</td><td className="p-3">{Number(item.quantity_ordered)}</td><td className="p-3">{Number(item.quantity_received)}</td><td className="p-3">{Number(item.quantity_rejected)}</td><td className="p-3">{money(item.unit_cost,order.currency)}</td><td className="p-3 font-bold">{money(item.line_total,order.currency)}</td></tr>)}</tbody></table></section>
    <section className="mt-3 grid gap-3 lg:grid-cols-2"><article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Receipts</h2>{data.receipts.length?<ul className="mt-2 divide-y">{data.receipts.map((receipt)=><li key={receipt.id} className="py-2"><strong>{receipt.receipt_number}</strong><span className="ml-2 text-sm">{receipt.receipt_date}</span><span className="block text-xs text-[var(--muted-text)]">{receipt.supplier_delivery_reference??"No delivery reference"}</span></li>)}</ul>:<p className="mt-2 text-sm text-[var(--muted-text)]">No stock received yet.</p>}</article><article className="rounded-xl border bg-[var(--surface)] p-4"><h2 className="font-bold">Status history</h2><ul className="mt-2 divide-y">{data.events.map((event)=><li key={event.id} className="py-2 text-sm"><strong>{event.previous_status?`${label(event.previous_status)} → `:""}{label(event.new_status)}</strong><span className="block text-xs text-[var(--muted-text)]">{new Date(event.created_at).toLocaleString()} {event.note?`· ${event.note}`:""}</span></li>)}</ul></article></section>
  </DashboardShell>;
}
