"use client";
import { useMemo, useState } from "react";
import { createSaleAction } from "@/app/admin/sales/actions";

type Customer={id:string;full_name:string|null;email:string;phone:string|null;company_name:string|null};
type Product={id:string;name:string;sku:string;model_number:string|null;brand_id:string|null;product_type:string;regular_price:number|null;sale_price:number|null;serial_tracking_required:boolean};
type Variation={id:string;product_id:string;name:string|null;sku:string;regular_price:number|null;sale_price:number|null};
type Balance={product_id:string;variation_id:string|null;warehouse_id:string;available:number};
type Address={id:string;profile_id:string;recipient_name:string;address_line_1:string;city:string;country_code:string;is_default_shipping:boolean};
type Warehouse={id:string;code:string;name:string};
type Row={key:string;product_id:string;variation_id:string;quantity:string;unit_price:string;line_discount:string;discount_percent:string;reason:string;catalogue_price:number};
const field="mt-1 w-full rounded-lg border bg-[var(--surface)] px-3 py-2";

export function SaleBuilder({customers,products,variations,balances,warehouses,addresses}:{customers:Customer[];products:Product[];variations:Variation[];balances:Balance[];warehouses:Warehouse[];addresses:Address[]}) {
  const [customerId,setCustomerId]=useState(customers[0]?.id??""),[warehouseId,setWarehouseId]=useState(warehouses[0]?.id??""),[addressId,setAddressId]=useState("");
  const [search,setSearch]=useState(""),[rows,setRows]=useState<Row[]>([{key:crypto.randomUUID(),product_id:"",variation_id:"",quantity:"1",unit_price:"0",line_discount:"0",discount_percent:"0",reason:"",catalogue_price:0}]);
  const customer=customers.find(x=>x.id===customerId),customerAddresses=addresses.filter(x=>x.profile_id===customerId),choices=products.filter(x=>`${x.name} ${x.sku} ${x.model_number??""}`.toLowerCase().includes(search.toLowerCase())).slice(0,150);
  const selected=useMemo(()=>rows.map(row=>{const product=products.find(x=>x.id===row.product_id),variation=variations.find(x=>x.id===row.variation_id),available=balances.filter(x=>x.product_id===row.product_id&&x.warehouse_id===warehouseId&&(!row.variation_id||x.variation_id===row.variation_id)).reduce((n,x)=>n+Number(x.available),0),gross=Number(row.quantity||0)*Number(row.unit_price||0),discount=Math.min(gross,Number(row.line_discount||0)+gross*Number(row.discount_percent||0)/100);return{...row,product,variation,available,gross,discount,lineTotal:gross-discount}}),[rows,products,variations,balances,warehouseId]);
  const update=(key:string,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.key===key?{...row,...patch}:row));
  const payload=selected.filter(x=>x.product).map(x=>({product_id:x.product_id,variation_id:x.variation_id||null,warehouse_id:warehouseId,quantity:Number(x.quantity),unit_price:Number(x.unit_price),line_discount:x.discount,line_tax:0,price_overridden:Number(x.unit_price)!==x.catalogue_price,catalogue_price:x.catalogue_price,adjustment_reason:x.reason}));
  const subtotal=selected.reduce((n,x)=>n+x.lineTotal,0);
  return <form action={createSaleAction} className="space-y-4"><input type="hidden" name="items" value={JSON.stringify(payload)}/>
    <section className="grid gap-4 rounded-xl border bg-[var(--surface)] p-4 lg:grid-cols-3">
      <label className="text-sm font-semibold">Customer<select name="customer_id" value={customerId} onChange={e=>{setCustomerId(e.target.value);setAddressId("")}} className={field} required>{customers.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email} · {x.email}</option>)}</select></label>
      <label className="text-sm font-semibold">Sales source<select name="sales_source" className={field}>{["website","facebook","whatsapp","phone","email","direct_office","existing_customer","sales_representative","referral","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>
      <label className="text-sm font-semibold">Expected delivery<input name="expected_delivery_date" type="date" className={field}/></label>
      <label className="text-sm font-semibold">Warehouse<select name="warehouse_id" value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className={field} required>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>
      <label className="text-sm font-semibold">Delivery address<select name="address_id" value={addressId} onChange={e=>setAddressId(e.target.value)} className={field}><option value="">Enter below</option>{customerAddresses.map(x=><option key={x.id} value={x.id}>{x.recipient_name}, {x.address_line_1}</option>)}</select></label>
      <label className="text-sm font-semibold">Billing address<select name="billing_address_id" className={field}><option value="">Same as delivery</option>{customerAddresses.map(x=><option key={x.id} value={x.id}>{x.recipient_name}, {x.address_line_1}</option>)}</select></label>
      {!addressId?<><input name="recipient_name" placeholder="Recipient name" defaultValue={customer?.full_name??""} className={field} required/><input name="phone" placeholder="Phone" defaultValue={customer?.phone??""} className={field} required/><input name="address_line_1" placeholder="Delivery address" className={field} required/><input name="city" placeholder="City" className={field} required/><input name="country_code" defaultValue="BD" maxLength={2} className={field} required/></>:null}
    </section>
    <section className="rounded-xl border bg-[var(--surface)] p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">Products and pricing</h2><p className="text-sm text-[var(--muted-text)]">Search by product name, model, SKU or brand text. Stock is validated again on confirmation.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products" className="rounded-lg border px-3 py-2"/></div>
      <div className="mt-3 space-y-3">{selected.map(row=><article key={row.key} className="grid gap-2 rounded-xl border p-3 lg:grid-cols-[2fr_1fr_.6fr_.8fr_.7fr_.7fr_auto]">
        <label className="text-xs font-semibold">Product<select value={row.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value),price=Number(p?.sale_price??p?.regular_price??0);update(row.key,{product_id:e.target.value,variation_id:"",unit_price:String(price),catalogue_price:price})}} className={field} required><option value="">Choose product</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}{x.serial_tracking_required?" · Serialized":""}</option>)}</select></label>
        <label className="text-xs font-semibold">Variation<select value={row.variation_id} onChange={e=>{const v=variations.find(x=>x.id===e.target.value),price=Number(v?.sale_price??v?.regular_price??row.catalogue_price);update(row.key,{variation_id:e.target.value,unit_price:String(price),catalogue_price:price})}} className={field}><option value="">None</option>{variations.filter(x=>x.product_id===row.product_id).map(x=><option key={x.id} value={x.id}>{x.name||x.sku}</option>)}</select></label>
        <label className="text-xs font-semibold">Qty<input type="number" min="1" max={row.available} step={row.product?.serial_tracking_required?1:.0001} value={row.quantity} onChange={e=>update(row.key,{quantity:e.target.value})} className={field}/><span className={Number(row.quantity)>row.available?"text-red-700":"text-[var(--muted-text)]"}>Available {row.available}</span></label>
        <label className="text-xs font-semibold">Unit BDT<input type="number" min="0" step=".01" value={row.unit_price} onChange={e=>update(row.key,{unit_price:e.target.value})} className={field}/></label>
        <label className="text-xs font-semibold">Discount %<input type="number" min="0" max="100" step=".01" value={row.discount_percent} onChange={e=>update(row.key,{discount_percent:e.target.value})} className={field}/></label>
        <label className="text-xs font-semibold">Fixed discount<input type="number" min="0" step=".01" value={row.line_discount} onChange={e=>update(row.key,{line_discount:e.target.value})} className={field}/><span>Line {row.lineTotal.toFixed(2)}</span></label>
        <button type="button" disabled={rows.length===1} onClick={()=>setRows(x=>x.filter(y=>y.key!==row.key))} className="self-center rounded-lg border px-3 py-2 disabled:opacity-40">Remove</button>
        {(Number(row.unit_price)!==row.catalogue_price||row.discount>0)?<label className="text-xs font-semibold lg:col-span-full">Adjustment reason<input value={row.reason} onChange={e=>update(row.key,{reason:e.target.value})} required className={field}/></label>:null}
      </article>)}</div><button type="button" onClick={()=>setRows(x=>[...x,{key:crypto.randomUUID(),product_id:"",variation_id:"",quantity:"1",unit_price:"0",line_discount:"0",discount_percent:"0",reason:"",catalogue_price:0}])} className="mt-3 rounded-lg border px-4 py-2 font-semibold">+ Add product</button>
    </section>
    <section className="grid gap-3 rounded-xl border bg-[var(--surface)] p-4 md:grid-cols-3"><label className="text-sm">Order discount<input name="discount_amount" type="number" min="0" step=".01" defaultValue="0" className={field}/></label><label className="text-sm">Shipping charge<input name="shipping_amount" type="number" min="0" step=".01" defaultValue="0" className={field}/></label><label className="text-sm">Installation/service<input name="service_amount" type="number" min="0" step=".01" defaultValue="0" className={field}/></label><label className="text-sm">VAT/tax<input name="tax_amount" type="number" min="0" step=".01" defaultValue="0" className={field}/></label><label className="text-sm md:col-span-2">Discount reason<input name="discount_reason" className={field}/></label><label className="text-sm md:col-span-3">Customer note<textarea name="customer_notes" className={field}/></label><label className="text-sm md:col-span-3">Internal note<textarea name="internal_notes" className={field}/></label><div className="md:col-span-3 text-right text-xl font-bold">Items after line discounts: {subtotal.toFixed(2)} BDT</div></section>
    <div className="flex justify-end"><button className="rounded-lg bg-[var(--primary)] px-5 py-3 font-bold text-[var(--primary-foreground)]">Create draft sale</button></div>
  </form>;
}
