-- SEN product and multi-warehouse inventory foundation. Additive only.

create table public.product_categories(id uuid primary key default gen_random_uuid(),parent_id uuid references public.product_categories(id) on delete restrict,name text not null,slug text not null unique,description text,sen_business_category text not null default 'Others' check(sen_business_category in('Networking','Energy','Medical Equipment','Others')),is_active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.brands(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,description text,website_url text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_tags(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,created_at timestamptz not null default now());
create table public.attributes(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,description text,is_active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.attribute_values(id uuid primary key default gen_random_uuid(),attribute_id uuid not null references public.attributes(id) on delete cascade,value text not null,slug text not null,sort_order integer not null default 0,created_at timestamptz not null default now(),unique(attribute_id,value),unique(attribute_id,slug));

create table public.warehouses(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,country_code text not null,country_name text not null,address text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.warehouse_locations(id uuid primary key default gen_random_uuid(),warehouse_id uuid not null references public.warehouses(id) on delete restrict,code text not null,name text not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(warehouse_id,code));

create table public.products(
 id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,sku text not null unique,barcode text unique,manufacturer_part_number text,
 product_type text not null default 'simple' check(product_type in('simple','variable')),status text not null default 'draft' check(status in('draft','active','archived')),featured boolean not null default false,sen_business_category text not null default 'Others' check(sen_business_category in('Networking','Energy','Medical Equipment','Others')),brand_id uuid references public.brands(id) on delete set null,
 short_description text,description text,specifications jsonb not null default '{}'::jsonb,internal_notes text,warranty_information text,datasheet_url text,
 purchase_cost numeric(18,4) check(purchase_cost>=0),regular_price numeric(18,4) check(regular_price>=0),sale_price numeric(18,4) check(sale_price>=0 and (regular_price is null or sale_price<=regular_price)),currency char(3) not null default 'USD',tax_status text not null default 'taxable',tax_class text,
 weight numeric(18,4) check(weight>=0),length numeric(18,4) check(length>=0),width numeric(18,4) check(width>=0),height numeric(18,4) check(height>=0),shipping_class text,country_of_origin text,
 manage_stock boolean not null default true,stock_status text not null default 'in_stock' check(stock_status in('in_stock','out_of_stock','on_backorder')),low_stock_threshold numeric(18,4) not null default 0 check(low_stock_threshold>=0),allow_backorders boolean not null default false,sold_individually boolean not null default false,serial_tracking_required boolean not null default false,batch_tracking_enabled boolean not null default false,default_warehouse_id uuid references public.warehouses(id) on delete set null,public_catalogue_visible boolean not null default false,
 created_by uuid references public.profiles(id) on delete set null,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.product_category_assignments(product_id uuid not null references public.products(id) on delete cascade,category_id uuid not null references public.product_categories(id) on delete restrict,is_primary boolean not null default false,created_at timestamptz not null default now(),primary key(product_id,category_id));
create unique index product_one_primary_category_idx on public.product_category_assignments(product_id) where is_primary;
create table public.product_tag_assignments(product_id uuid not null references public.products(id) on delete cascade,tag_id uuid not null references public.product_tags(id) on delete cascade,created_at timestamptz not null default now(),primary key(product_id,tag_id));
create table public.product_attributes(product_id uuid not null references public.products(id) on delete cascade,attribute_id uuid not null references public.attributes(id) on delete restrict,is_variation boolean not null default false,is_visible boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),primary key(product_id,attribute_id));

create table public.product_variations(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete restrict,sku text not null unique,barcode text unique,status text not null default 'active' check(status in('active','archived')),purchase_cost numeric(18,4) check(purchase_cost>=0),regular_price numeric(18,4) check(regular_price>=0),sale_price numeric(18,4) check(sale_price>=0 and (regular_price is null or sale_price<=regular_price)),manage_stock boolean not null default true,stock_status text not null default 'in_stock' check(stock_status in('in_stock','out_of_stock','on_backorder')),low_stock_threshold numeric(18,4) not null default 0 check(low_stock_threshold>=0),allow_backorders boolean not null default false,image_url text,weight numeric(18,4) check(weight>=0),length numeric(18,4) check(length>=0),width numeric(18,4) check(width>=0),height numeric(18,4) check(height>=0),combination_key text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(product_id,combination_key));
create or replace function public.validate_product_variation() returns trigger language plpgsql set search_path='' as $$ declare parent public.products%rowtype; begin select * into parent from public.products where id=new.product_id; if parent.product_type<>'variable' then raise exception 'Variations require a variable parent product'; end if; if parent.manage_stock and new.manage_stock then raise exception 'Stock cannot be managed at both parent and variation level'; end if; return new; end $$;
create trigger validate_product_variation before insert or update on public.product_variations for each row execute function public.validate_product_variation();
create table public.variation_attribute_values(variation_id uuid not null references public.product_variations(id) on delete restrict,attribute_value_id uuid not null references public.attribute_values(id) on delete restrict,created_at timestamptz not null default now(),primary key(variation_id,attribute_value_id));
create table public.product_media(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,variation_id uuid references public.product_variations(id) on delete cascade,media_type text not null default 'image' check(media_type in('image','document')),storage_path text not null unique,alt_text text,sort_order integer not null default 0,is_primary boolean not null default false,mime_type text,file_size bigint check(file_size>=0 and file_size<=10485760),created_at timestamptz not null default now());
create unique index product_primary_media_idx on public.product_media(product_id) where is_primary and variation_id is null;

create table public.stock_adjustment_reasons(id uuid primary key default gen_random_uuid(),key text not null unique,name text not null,direction text not null check(direction in('increase','decrease','both')),is_active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now());
insert into public.stock_adjustment_reasons(key,name,direction,sort_order) values('opening_balance','Opening balance','increase',10),('manual_count','Manual count correction','both',20),('damage','Damaged stock','decrease',30),('customer_return','Customer return','increase',40),('supplier_return','Supplier return','decrease',50),('correction','Inventory correction','both',60) on conflict(key) do nothing;

create table public.inventory_balances(id uuid primary key default gen_random_uuid(),warehouse_id uuid not null references public.warehouses(id) on delete restrict,location_id uuid references public.warehouse_locations(id) on delete restrict,product_id uuid not null references public.products(id) on delete restrict,variation_id uuid references public.product_variations(id) on delete restrict,on_hand numeric(18,4) not null default 0 check(on_hand>=0),reserved numeric(18,4) not null default 0 check(reserved>=0),incoming numeric(18,4) not null default 0 check(incoming>=0),damaged numeric(18,4) not null default 0 check(damaged>=0),unavailable numeric(18,4) not null default 0 check(unavailable>=0),available numeric(18,4) generated always as (on_hand-reserved-damaged-unavailable) stored,updated_at timestamptz not null default now(),check(reserved+damaged+unavailable<=on_hand));
create unique index inventory_balance_product_idx on public.inventory_balances(warehouse_id,product_id) where variation_id is null and location_id is null;
create unique index inventory_balance_variation_idx on public.inventory_balances(warehouse_id,variation_id) where variation_id is not null and location_id is null;

create table public.inventory_movements(id uuid primary key default gen_random_uuid(),reference text not null unique,movement_type text not null check(movement_type in('opening_balance','purchase_receipt','manual_adjustment','warehouse_transfer','reservation','reservation_release','sale_allocation','customer_return','supplier_return','damage','correction')),status text not null default 'confirmed' check(status in('draft','confirmed','cancelled')),source_warehouse_id uuid references public.warehouses(id) on delete restrict,destination_warehouse_id uuid references public.warehouses(id) on delete restrict,reason_id uuid references public.stock_adjustment_reasons(id) on delete set null,notes text,initiated_by uuid not null references public.profiles(id) on delete restrict,confirmed_at timestamptz,created_at timestamptz not null default now(),check(source_warehouse_id is distinct from destination_warehouse_id or source_warehouse_id is null));
create table public.inventory_movement_items(id uuid primary key default gen_random_uuid(),movement_id uuid not null references public.inventory_movements(id) on delete restrict,product_id uuid not null references public.products(id) on delete restrict,variation_id uuid references public.product_variations(id) on delete restrict,warehouse_id uuid not null references public.warehouses(id) on delete restrict,quantity_delta numeric(18,4) not null check(quantity_delta<>0),balance_after numeric(18,4) not null check(balance_after>=0),created_at timestamptz not null default now());
create table public.inventory_reservations(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete restrict,variation_id uuid references public.product_variations(id) on delete restrict,warehouse_id uuid not null references public.warehouses(id) on delete restrict,quantity numeric(18,4) not null check(quantity>0),status text not null default 'active' check(status in('active','released','consumed','cancelled')),reference text,expires_at timestamptz,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.serial_numbers(id uuid primary key default gen_random_uuid(),manufacturer_serial text not null unique,sen_serial text unique,barcode_value text unique,product_id uuid not null references public.products(id) on delete restrict,variation_id uuid references public.product_variations(id) on delete restrict,warehouse_id uuid not null references public.warehouses(id) on delete restrict,location_id uuid references public.warehouse_locations(id) on delete restrict,status text not null default 'available' check(status in('available','reserved','sold','damaged','unavailable','transferred','removed')),condition text not null default 'new',acquisition_reference text,warranty_start date,warranty_end date,notes text,last_movement_id uuid references public.inventory_movements(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(warranty_end is null or warranty_start is null or warranty_end>=warranty_start));

create index products_status_idx on public.products(status); create index products_type_idx on public.products(product_type); create index products_brand_idx on public.products(brand_id); create index product_category_assignments_category_idx on public.product_category_assignments(category_id); create index inventory_balances_warehouse_idx on public.inventory_balances(warehouse_id); create index inventory_movements_created_idx on public.inventory_movements(created_at desc); create index inventory_movements_type_idx on public.inventory_movements(movement_type); create index serial_numbers_product_idx on public.serial_numbers(product_id); create index serial_numbers_warehouse_idx on public.serial_numbers(warehouse_id); create index serial_numbers_status_idx on public.serial_numbers(status); create index inventory_reservations_status_idx on public.inventory_reservations(status);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-media','product-media',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

do $$ declare t text; begin foreach t in array array['product_categories','brands','product_tags','attributes','attribute_values','warehouses','warehouse_locations','products','product_category_assignments','product_tag_assignments','product_attributes','product_variations','variation_attribute_values','product_media','stock_adjustment_reasons','inventory_balances','inventory_movements','inventory_movement_items','inventory_reservations','serial_numbers'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy "authorized staff read products" on public.products for select to authenticated using(public.current_user_has_permission('products.view') or public.current_user_has_permission('inventory.view'));
create policy "authorized staff read product categories" on public.product_categories for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read brands" on public.brands for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read tags" on public.product_tags for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read attributes" on public.attributes for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read attribute values" on public.attribute_values for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read category assignments" on public.product_category_assignments for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read tag assignments" on public.product_tag_assignments for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read product attributes" on public.product_attributes for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read variations" on public.product_variations for select to authenticated using(public.current_user_has_permission('products.view') or public.current_user_has_permission('inventory.view'));
create policy "authorized staff read variation values" on public.variation_attribute_values for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read product media" on public.product_media for select to authenticated using(public.current_user_has_permission('products.view'));
create policy "authorized staff read warehouses" on public.warehouses for select to authenticated using(public.current_user_has_permission('warehouses.view') or public.current_user_has_permission('inventory.view'));
create policy "authorized staff read warehouse locations" on public.warehouse_locations for select to authenticated using(public.current_user_has_permission('warehouses.view') or public.current_user_has_permission('inventory.view'));
create policy "authorized staff read adjustment reasons" on public.stock_adjustment_reasons for select to authenticated using(public.current_user_has_permission('inventory.view'));
create policy "authorized staff read balances" on public.inventory_balances for select to authenticated using(public.current_user_has_permission('inventory.view'));
create policy "authorized staff read movements" on public.inventory_movements for select to authenticated using(public.current_user_has_permission('inventory.view'));
create policy "authorized staff read movement items" on public.inventory_movement_items for select to authenticated using(public.current_user_has_permission('inventory.view'));
create policy "authorized staff read reservations" on public.inventory_reservations for select to authenticated using(public.current_user_has_permission('inventory.view'));
create policy "authorized staff read serials" on public.serial_numbers for select to authenticated using(public.current_user_has_permission('serials.view') or public.current_user_has_permission('inventory.view'));

create or replace function public.admin_adjust_inventory(actor_profile_id uuid,requested_warehouse_id uuid,requested_product_id uuid,requested_variation_id uuid,quantity_change numeric,requested_reason_id uuid,requested_notes text,requested_serials text[] default '{}') returns uuid language plpgsql security definer set search_path='' as $$
declare p public.products%rowtype; b public.inventory_balances%rowtype; m_id uuid:=gen_random_uuid(); new_on_hand numeric; actor_role public.account_role;
begin
 if quantity_change=0 then raise exception 'Quantity change cannot be zero'; end if;
 if not exists(select 1 from public.effective_permissions_for_profile(actor_profile_id) where permission_key='inventory.adjust_stock') then raise exception 'Permission denied'; end if;
 select * into p from public.products where id=requested_product_id and status<>'archived'; if p.id is null then raise exception 'Product not found'; end if;
 if not exists(select 1 from public.warehouses where id=requested_warehouse_id and is_active) then raise exception 'Active warehouse required'; end if;
 if requested_variation_id is not null and not exists(select 1 from public.product_variations where id=requested_variation_id and product_id=requested_product_id and status='active') then raise exception 'Invalid variation'; end if;
 if p.serial_tracking_required and (quantity_change<>trunc(quantity_change) or coalesce(array_length(requested_serials,1),0)<>abs(quantity_change)::integer or (select count(distinct trim(s)) from unnest(requested_serials) s)<>abs(quantity_change)::integer) then raise exception 'Every serialized unit requires one unique serial number'; end if;
 if p.serial_tracking_required and quantity_change<0 and (select count(*) from public.serial_numbers where manufacturer_serial=any(requested_serials) and product_id=requested_product_id and warehouse_id=requested_warehouse_id and status='available')<>abs(quantity_change)::integer then raise exception 'One or more serials are unavailable'; end if;
 insert into public.inventory_balances(warehouse_id,product_id,variation_id) values(requested_warehouse_id,requested_product_id,requested_variation_id) on conflict do nothing;
 select * into b from public.inventory_balances where warehouse_id=requested_warehouse_id and product_id=requested_product_id and variation_id is not distinct from requested_variation_id and location_id is null for update;
 new_on_hand:=b.on_hand+quantity_change; if new_on_hand<0 or new_on_hand<b.reserved+b.damaged+b.unavailable then raise exception 'Insufficient available stock'; end if;
 select role into actor_role from public.profiles where id=actor_profile_id;
 insert into public.inventory_movements(id,reference,movement_type,status,destination_warehouse_id,source_warehouse_id,reason_id,notes,initiated_by,confirmed_at) values(m_id,'ADJ-'||upper(substr(replace(m_id::text,'-',''),1,12)),case when b.on_hand=0 and quantity_change>0 then 'opening_balance' else 'manual_adjustment' end,'confirmed',case when quantity_change>0 then requested_warehouse_id end,case when quantity_change<0 then requested_warehouse_id end,requested_reason_id,left(requested_notes,1000),actor_profile_id,now());
 update public.inventory_balances set on_hand=new_on_hand,updated_at=now() where id=b.id;
 insert into public.inventory_movement_items(movement_id,product_id,variation_id,warehouse_id,quantity_delta,balance_after) values(m_id,requested_product_id,requested_variation_id,requested_warehouse_id,quantity_change,new_on_hand);
 if p.serial_tracking_required and quantity_change>0 then insert into public.serial_numbers(manufacturer_serial,product_id,variation_id,warehouse_id,last_movement_id) select distinct trim(s),requested_product_id,requested_variation_id,requested_warehouse_id,m_id from unnest(requested_serials) s; end if;
 if p.serial_tracking_required and quantity_change<0 then update public.serial_numbers set status='removed',last_movement_id=m_id,updated_at=now() where manufacturer_serial=any(requested_serials) and product_id=requested_product_id and warehouse_id=requested_warehouse_id and status='available'; if found is false then raise exception 'One or more serials are unavailable'; end if; end if;
 insert into public.audit_logs(actor_id,actor_role,action,module,entity_type,entity_id,description,new_values) values(actor_profile_id,actor_role,'inventory.adjusted','inventory','inventory_movement',m_id::text,'Inventory quantity adjusted.',jsonb_build_object('product_id',requested_product_id,'variation_id',requested_variation_id,'warehouse_id',requested_warehouse_id,'quantity_change',quantity_change)); return m_id;
end $$;

create or replace function public.admin_transfer_inventory(actor_profile_id uuid,source_id uuid,destination_id uuid,requested_product_id uuid,requested_variation_id uuid,transfer_quantity numeric,requested_notes text,requested_serials text[] default '{}') returns uuid language plpgsql security definer set search_path='' as $$
declare p public.products%rowtype; src public.inventory_balances%rowtype; dst public.inventory_balances%rowtype; m_id uuid:=gen_random_uuid(); actor_role public.account_role;
begin
 if source_id=destination_id or transfer_quantity<=0 then raise exception 'A positive transfer between different warehouses is required'; end if;
 if not exists(select 1 from public.effective_permissions_for_profile(actor_profile_id) where permission_key='inventory.transfer') then raise exception 'Permission denied'; end if;
 select * into p from public.products where id=requested_product_id and status<>'archived'; if p.id is null then raise exception 'Product not found'; end if;
 if (select count(*) from public.warehouses where id in(source_id,destination_id) and is_active)<>2 then raise exception 'Two active warehouses are required'; end if;
 select * into src from public.inventory_balances where warehouse_id=source_id and product_id=requested_product_id and variation_id is not distinct from requested_variation_id and location_id is null for update; if src.id is null or src.available<transfer_quantity then raise exception 'Insufficient available source stock'; end if;
 if p.serial_tracking_required and (transfer_quantity<>trunc(transfer_quantity) or coalesce(array_length(requested_serials,1),0)<>transfer_quantity::integer or (select count(distinct trim(s)) from unnest(requested_serials) s)<>transfer_quantity::integer) then raise exception 'Every serialized unit must be selected'; end if;
 if p.serial_tracking_required and (select count(*) from public.serial_numbers where manufacturer_serial=any(requested_serials) and product_id=requested_product_id and warehouse_id=source_id and status='available')<>transfer_quantity::integer then raise exception 'One or more serials are unavailable'; end if;
 insert into public.inventory_balances(warehouse_id,product_id,variation_id) values(destination_id,requested_product_id,requested_variation_id) on conflict do nothing;
 select * into dst from public.inventory_balances where warehouse_id=destination_id and product_id=requested_product_id and variation_id is not distinct from requested_variation_id and location_id is null for update;
 select role into actor_role from public.profiles where id=actor_profile_id;
 insert into public.inventory_movements(id,reference,movement_type,status,source_warehouse_id,destination_warehouse_id,notes,initiated_by,confirmed_at) values(m_id,'TRF-'||upper(substr(replace(m_id::text,'-',''),1,12)),'warehouse_transfer','confirmed',source_id,destination_id,left(requested_notes,1000),actor_profile_id,now());
 update public.inventory_balances set on_hand=on_hand-transfer_quantity,updated_at=now() where id=src.id; update public.inventory_balances set on_hand=on_hand+transfer_quantity,updated_at=now() where id=dst.id;
 insert into public.inventory_movement_items(movement_id,product_id,variation_id,warehouse_id,quantity_delta,balance_after) values(m_id,requested_product_id,requested_variation_id,source_id,-transfer_quantity,src.on_hand-transfer_quantity),(m_id,requested_product_id,requested_variation_id,destination_id,transfer_quantity,dst.on_hand+transfer_quantity);
 if p.serial_tracking_required then update public.serial_numbers set warehouse_id=destination_id,last_movement_id=m_id,status='available',updated_at=now() where manufacturer_serial=any(requested_serials) and product_id=requested_product_id and warehouse_id=source_id and status='available'; if found is false then raise exception 'One or more serials are unavailable'; end if; end if;
 insert into public.audit_logs(actor_id,actor_role,action,module,entity_type,entity_id,description,new_values) values(actor_profile_id,actor_role,'inventory.transferred','inventory','inventory_movement',m_id::text,'Inventory transferred between warehouses.',jsonb_build_object('product_id',requested_product_id,'variation_id',requested_variation_id,'source_warehouse_id',source_id,'destination_warehouse_id',destination_id,'quantity',transfer_quantity)); return m_id;
end $$;

revoke all on function public.admin_adjust_inventory(uuid,uuid,uuid,uuid,numeric,uuid,text,text[]) from public,anon,authenticated; grant execute on function public.admin_adjust_inventory(uuid,uuid,uuid,uuid,numeric,uuid,text,text[]) to service_role;
revoke all on function public.admin_transfer_inventory(uuid,uuid,uuid,uuid,uuid,numeric,text,text[]) from public,anon,authenticated; grant execute on function public.admin_transfer_inventory(uuid,uuid,uuid,uuid,uuid,numeric,text,text[]) to service_role;
update public.app_modules set is_implemented=true,updated_at=now() where key in('products','inventory','warehouses','serials');
