import { connection } from "next/server";
import Link from "next/link";
import { DashboardShell } from "@/components/dashboard/Shell";
import { requireAnyPermission } from "@/lib/auth/permissions";
import { getSalesDashboard } from "@/lib/sales/data";
import { dateTime, label, money } from "@/lib/orders/types";

export const dynamic="force-dynamic";
const statuses=["draft","confirmed","processing","partially_allocated","allocated","packing","partially_shipped","shipped","delivered","cancelled"];
const payments=["unpaid","partially_paid","paid","overpaid","refunded"];
export default async function SalesPage({searchParams}:{searchParams:Promise<{q?:string;customer?:string;employee?:string;status?:string;payment?:string;date?:string;page?:string}>}) {
  await connection();
  const {profile,permissions}=await requireAnyPermission(["sales.view","sales.view_all","sales.view_own"]);
  const params=await searchParams,own=profile.role==="employee"&&!permissions.has("sales.view_all")&&!permissions.has("sales.view")?profile.id:undefined;
  const data=await getSalesDashboard({...params,ownProfileId:own});
  const cards=[["Today's sales",money(data.metrics.today)],["This month",money(data.metrics.month)],["Pending",data.metrics.pending],["Awaiting payment",data.metrics.awaitingPayment],["Partially paid",data.metrics.partiallyPaid],["Ready to ship",data.metrics.readyToShip],["Completed",data.metrics.completed],["Outstanding",money(data.metrics.outstanding)]];
  return <DashboardShell admin={profile.role==="admin"} employeePermissions={profile.role==="employee"?permissions:undefined} title="Sales" subtitle="Customer sales, payments, stock reservation and fulfilment in one operational view.">
    <section className="grid grid-cols-2 gap-2 md:grid-cols-4 xl:grid-cols-8">{cards.map(([name,value])=><article key={name} className="rounded-xl border border-l-4 border-l-cyan-500 bg-[var(--surface)] p-3 shadow-sm"><p className="text-xs text-[var(--muted-text)]">{name}</p><strong className="mt-1 block text-xl">{value}</strong></article>)}</section>
    <div className="mt-3 flex flex-wrap gap-2"><Link href="/admin/sales/new" className="rounded-lg bg-[var(--primary)] px-4 py-2 font-bold text-[var(--primary-foreground)]">Create Sale</Link><Link href="/admin/sales" className="rounded-lg border px-4 py-2 font-semibold">View All Sales</Link><Link href="/admin/sales?payment=unpaid" className="rounded-lg border px-4 py-2 font-semibold">Record Payment</Link><Link href="/admin/sales?payment=partially_paid" className="rounded-lg border px-4 py-2 font-semibold">View Outstanding Sales</Link></div>
    <form className="mt-3 grid gap-2 rounded-xl border bg-[var(--surface)] p-3 md:grid-cols-3 xl:grid-cols-6"><input name="q" defaultValue={params.q} placeholder="Sale number" className="rounded-lg border px-3 py-2"/><input name="date" type="date" defaultValue={params.date} className="rounded-lg border px-3 py-2"/><select name="customer" defaultValue={params.customer} className="rounded-lg border px-3 py-2"><option value="">All customers</option>{data.customers.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</select><select name="employee" defaultValue={params.employee} className="rounded-lg border px-3 py-2"><option value="">All employees</option>{data.employees.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</select><select name="status" defaultValue={params.status} className="rounded-lg border px-3 py-2"><option value="">All statuses</option>{statuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select name="payment" defaultValue={params.payment} className="rounded-lg border px-3 py-2"><option value="">All payments</option>{payments.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white xl:col-start-6">Apply filters</button></form>
    <div className="mt-3 overflow-x-auto rounded-xl border bg-[var(--surface)]"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-[var(--muted-surface)]"><tr>{["Sale","Customer","Employee","Total","Paid","Outstanding","Payment","Inventory","Shipment","Status","Date",""].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.sales.map(sale=>{const customer=sale.customer as {full_name:string|null;email:string}|null,employee=sale.employee as {full_name:string|null;email:string}|null,shipments=sale.shipments as {status:string}[]|null;return <tr key={sale.id} className="border-t hover:bg-[var(--muted-surface)]"><td className="p-3 font-bold">{sale.order_number}</td><td>{customer?.full_name||customer?.email}</td><td>{employee?.full_name||employee?.email}</td><td>{money(sale.total_amount,sale.currency)}</td><td>{money(sale.paid_amount,sale.currency)}</td><td>{money(Math.max(Number(sale.total_amount)-Number(sale.paid_amount),0),sale.currency)}</td><td>{label(sale.payment_status)}</td><td>{sale.status==="draft"?"Not reserved":sale.status==="cancelled"?"Released":"Reserved"}</td><td>{shipments?.length?label(shipments[0].status):"Not created"}</td><td>{label(sale.status)}</td><td>{dateTime(sale.created_at)}</td><td><a href={`/admin/sales/${sale.id}`} className="rounded-lg border px-3 py-2 font-semibold">Open</a></td></tr>})}</tbody></table>{!data.sales.length?<p className="p-10 text-center text-[var(--muted-text)]">No sales match these filters.</p>:null}</div>
    <div className="mt-3 flex justify-between text-sm"><span>{data.count} sale(s)</span><div>{data.page>1?<a href={`?page=${data.page-1}`} className="rounded border px-3 py-1">Previous</a>:null}{data.page*data.size<data.count?<a href={`?page=${data.page+1}`} className="ml-2 rounded border px-3 py-1">Next</a>:null}</div></div>
  </DashboardShell>;
}
