"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requirePermission } from "@/lib/auth/permissions";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { writeAuditLog } from "@/lib/audit/log";
import { requiredText, uuidOrNull } from "@/lib/inventory/validation";

const serials = (form: FormData) => [...new Set(String(form.get("serials") ?? "").split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean))].slice(0, 500);
const destination = (type: "success" | "error", message: string) => `/admin/inventory/adjustments/new?${type}=${encodeURIComponent(message)}`;
async function resolveSerializedInput(db:ReturnType<typeof createSupabaseAdminClient>,input:string[]){if(!input.length)return[];const normalized=input.map((value)=>value.replace(/[^A-Za-z0-9]/g,"").toUpperCase());const[senResult,manufacturerResult]=await Promise.all([db.from("serial_numbers").select("id,sen_serial,manufacturer_serial_normalized").in("sen_serial",input).limit(500),db.from("serial_numbers").select("id,sen_serial,manufacturer_serial_normalized").in("manufacturer_serial_normalized",normalized).limit(500)]);if(senResult.error||manufacturerResult.error)throw new Error("Unable to validate selected serials.");return [...new Map([...(senResult.data??[]),...(manufacturerResult.data??[])].map((item)=>[item.id,item])).values()];}

export async function adjustInventoryAction(form: FormData) {
  const { profile } = await requirePermission("inventory.adjust_stock");
  const warehouse = uuidOrNull(form.get("warehouse_id")), product = uuidOrNull(form.get("product_id")), variation = uuidOrNull(form.get("variation_id")), reason = uuidOrNull(form.get("reason_id")), change = Number(form.get("quantity_change")), notes = String(form.get("notes") ?? "").slice(0, 1000);
  if (!warehouse || !product || !reason || !Number.isFinite(change) || change === 0) redirect(destination("error", "Warehouse, product, reason, and nonzero quantity are required."));
  const db = createSupabaseAdminClient();
  const input=serials(form);const{data:productRecord,error:productError}=await db.from("products").select("serial_tracking_required").eq("id",product).maybeSingle();if(productError||!productRecord)redirect(destination("error","Unable to validate the selected product."));let data,error;if(productRecord.serial_tracking_required){if(!Number.isInteger(change))redirect(destination("error","Serialized quantity must be a whole number."));let selected:Array<{id:string}>=[];try{selected=await resolveSerializedInput(db,input);}catch{redirect(destination("error","Unable to validate selected serials."));}if(change<0&&selected.length!==Math.abs(change))redirect(destination("error","Resolve and select exactly one existing serial for every removed unit."));const result=await db.rpc("admin_adjust_serialized_inventory",{actor_profile_id:profile.id,requested_warehouse_id:warehouse,requested_product_id:product,requested_variation_id:variation,quantity_change:change,requested_reason_id:reason,requested_notes:notes,requested_serial_ids:selected.map((item)=>item.id),requested_manufacturer_serials:selected.length?[]:input});data=result.data;error=result.error;}else{const result=await db.rpc("admin_adjust_inventory", { actor_profile_id: profile.id, requested_warehouse_id: warehouse, requested_product_id: product, requested_variation_id: variation, quantity_change: change, requested_reason_id: reason, requested_notes: notes, requested_serials: input });data=result.data;error=result.error;}
  if (error) {
    console.error("Inventory adjustment failed", { code: error.code, message: error.message });
    const safe = /serial|Insufficient|Quantity|reason only permits|Active adjustment reason|Invalid variation/i.test(error.message) ? error.message : "Unable to adjust inventory.";
    redirect(destination("error", safe));
  }
  revalidatePath("/admin/inventory"); redirect(`/admin/inventory/movements/${data}?success=${encodeURIComponent("Inventory adjusted.")}`);
}

export async function transferInventoryAction(form: FormData) {
  const { profile } = await requirePermission("inventory.transfer");
  const source = uuidOrNull(form.get("source_id")), destinationId = uuidOrNull(form.get("destination_id")), product = uuidOrNull(form.get("product_id")), variation = uuidOrNull(form.get("variation_id")), quantity = Number(form.get("quantity"));
  if (!source || !destinationId || !product || !Number.isFinite(quantity) || quantity <= 0) redirect(destination("error", "Source, destination, product, and positive quantity are required."));
  const db = createSupabaseAdminClient();
  const input=serials(form),notes=String(form.get("notes")??"").slice(0,1000);const{data:productRecord,error:productError}=await db.from("products").select("serial_tracking_required").eq("id",product).maybeSingle();if(productError||!productRecord)redirect(destination("error","Unable to validate the selected product."));let data,error;if(productRecord.serial_tracking_required){if(!Number.isInteger(quantity))redirect(destination("error","Serialized quantity must be a whole number."));let selected:Array<{id:string}>=[];try{selected=await resolveSerializedInput(db,input);}catch{redirect(destination("error","Unable to validate selected serials."));}if(selected.length!==quantity)redirect(destination("error","Resolve and select exactly one existing serial for every transferred unit."));const result=await db.rpc("admin_transfer_serialized_inventory",{actor_profile_id:profile.id,source_id:source,destination_id:destinationId,requested_product_id:product,requested_variation_id:variation,transfer_quantity:quantity,requested_notes:notes,requested_serial_ids:selected.map((item)=>item.id)});data=result.data;error=result.error;}else{const result=await db.rpc("admin_transfer_inventory", { actor_profile_id: profile.id, source_id: source, destination_id: destinationId, requested_product_id: product, requested_variation_id: variation, transfer_quantity: quantity, requested_notes: notes, requested_serials: input });data=result.data;error=result.error;}
  if (error) {
    console.error("Inventory transfer failed", { code: error.code, message: error.message });
    if (["40P01", "40001"].includes(error.code ?? "")) redirect(destination("error", "The stock changed during this transfer. No movement was created; review the balances and submit again."));
    const safe = /serial|Insufficient|different warehouses|positive transfer|Invalid variation|active warehouses/i.test(error.message) ? error.message : "Unable to transfer inventory.";
    redirect(destination("error", safe));
  }
  revalidatePath("/admin/inventory"); redirect(`/admin/inventory/movements/${data}?success=${encodeURIComponent("Inventory transferred.")}`);
}

export async function createWarehouseAction(form: FormData) { const { profile } = await requirePermission("warehouses.create"); const db = createSupabaseAdminClient(), data = { code: requiredText(form, "code", 30).toUpperCase(), name: requiredText(form, "name", 120), country_code: requiredText(form, "country_code", 2).toUpperCase(), country_name: requiredText(form, "country_name", 100), address: String(form.get("address") ?? "").slice(0, 500) }; const { data: created, error } = await db.from("warehouses").insert(data).select("id").single(); if (error || !created) redirect(`/admin/warehouses?error=${encodeURIComponent("Unable to create warehouse. Check its code.")}`); await writeAuditLog({ actorId: profile.id, actorRole: profile.role, action: "warehouse.created", module: "warehouses", entityType: "warehouse", entityId: created.id, description: "Warehouse created.", newValues: { code: data.code, name: data.name, country_code: data.country_code } }); revalidatePath("/admin/warehouses"); redirect(`/admin/warehouses/${created.id}?success=${encodeURIComponent("Warehouse created.")}`); }
export async function createWarehouseLocationAction(warehouseId: string, form: FormData) { const { profile } = await requirePermission("warehouses.manage_locations"); const db = createSupabaseAdminClient(), data = { warehouse_id: warehouseId, code: requiredText(form, "code", 40).toUpperCase(), name: requiredText(form, "name", 120) }; const { data: created, error } = await db.from("warehouse_locations").insert(data).select("id").single(); if (error || !created) redirect(`/admin/warehouses/${warehouseId}?error=${encodeURIComponent("Unable to add location.")}`); await writeAuditLog({ actorId: profile.id, actorRole: profile.role, action: "warehouse.location_created", module: "warehouses", entityType: "warehouse_location", entityId: created.id, description: "Warehouse location created.", newValues: { warehouse_id: warehouseId, code: data.code, name: data.name } }); revalidatePath(`/admin/warehouses/${warehouseId}`); redirect(`/admin/warehouses/${warehouseId}?success=${encodeURIComponent("Location added.")}`); }
